### ISSUE TITLE
Including upcoming games on list pages

### ISSUE THREAD

**Issue by benbarden** [benbarden/switchscores#101]
After redoing the tag list page to use a better layout, I remembered that any upcoming/unreleased games with tags will be included in the tag count, but won't be on the list page.

E.g. "Maze" showed 14 on the tag list, but only 13 games when you click through.

On #86 we talked about changing the layout to match category pages, but I had an idea that might be simpler. See here:
https://www.switchscores.com/games/by-tag/maze

![Screenshot 2021-05-16 at 21 27 55](https://user-images.githubusercontent.com/628824/118411669-9d432780-b68d-11eb-8ba9-4c27c548c9c0.png)

The list now has a similar layout to the other lists (though not the tabbed layout from the category list). If the game isn't yet released, it will say "To be released" and the 0/3 reviews bit is removed.

I've also changed the database query to ignore whether a game is released or not.

Thoughts on this, before I look at doing this for other game lists?

**Comment by cosmo0** [comment]
Cool!

**Comment by benbarden** [comment]
A small bug: if an upcoming game has 3 reviews and is ranked, the score no longer displays. I will get that to display as long as it's not de-listed.

**Comment by benbarden** [comment]
That bug is now fixed. I've also applied the new layout to the following pages:

- Recent releases
- Upcoming
- By title
- By series
- By collection
