### ISSUE TITLE
Remove developers from the DB

### ISSUE THREAD

**Issue by cosmo0** [benbarden/switchscores#103]
It looks like Nintendo removed developers from their DB/API ? It wasn't much used anyway, and full of errors, and above all, mostly useless.

Do you think it's still useful to have a field with this info? I think the publisher is enough, and it would remove useless entries in the companies list.

**Comment by benbarden** [comment]
They never had developers in the UK/EU API, but they are in the US API. We definitely don't need to fill them all in, but I think there's a benefit in keeping the current setup when devs want to login to the site - especially if they are developer/publishers.

**Comment by cosmo0** [comment]
Is there any developer with a SwitchScore account ? What can they do ?

**Comment by benbarden** [comment]
Yes, a few people can login. It's the same benefit as for publishers - they can see contact details of reviewers (if they agree to share their details). There is also some code to show which games are linked to the dev/pub, and to get in touch if we are missing any of their games. That code isn't active though - it's part of an older dashboard I was going to redo, but so far there hasn't been much interest.

**Comment by benbarden** [comment]
I'm going to close this - there's some value in having this data, but it's ok if we don't have it for every game.
