### ISSUE TITLE
Bundles, special editions, and game stats

### ISSUE THREAD

**Issue by benbarden** [benbarden/switchscores#104]
Have a look at this page - https://www.switchscores.com/staff/data-sources/nintendo-co-uk/ignored

These are the games from the Nintendo.co.uk API that I have ignored, usually because they are bundles or special editions of existing games.

However, some sites do review these, and it could be useful to list them on the site. For bundles, we do have a "bundles" category.

The main reason I didn't want to list them on the site is because the total game count on the homepage counts every game, but I could easily add a checkbox "Include in total games count" (default to yes) and then this could be unchecked for bundles of games that are already available separately. That's a small change and also only a minor reason not to include those games on the site.

I will still keep duplicates off the site, as a few titles either get listed twice, or get removed and then re-listed under a new id.

Any thoughts on this?

**Comment by cosmo0** [comment]
I don't think bundles (as in https://www.switchscores.com/games/by-category/bundle ) are very useful as it stands. Maybe if there was a way to link to the included games, and the bundles would have a rating based on the included games?

I don't think anyone cares about the total games count.

I see 2 ignored items that shouldn't:

- Minecraft Nintendo Switch Edition: not technically the same as just-Minecraft (it's an older, more limited version)
- Elena Temple Definitive Edition: not exactly the same game, includes 2 new worlds. I've played both, they're different enough to deserve two spots.

I know we already had this discussion. I don't remember why you didn't want to un-ignore Elena Temple DE (I don't think anyone cares about an outdated Minecraft version).

I think we should ignore the free version of Lost Lands Dark Overlord: https://www.switchscores.com/games/5252/lost-lands-dark-overlord

Plus there are a lot of "bundles". I don't understand why we have a "bundle" category while some bundles are ignored. Either ignore them all or none?

**Comment by benbarden** [comment]
I've ignored the bundles that appear on the eShop with a "bundle" label on the image - so where it's a combination of items that you can (usually) get separately as well. The ones I've added do not have that label, and are distinct entries on the eShop. Perhaps the best thing would be to ignore those too, and only think about including them if they have reviews. Of the 39 in that category, only 2 have reviews - each with 1 review each.

Most people won't care about whether the total games count is exactly correct (so whether it's 5200 or 5400), but the overall count has been referenced a few times and compared to Wikipedia, which ignores a lot of games due to being non-notable. The main benefit of the count is as a gauge to how big the Switch library is, but in reality it's more of a stat to show how many titles Switch Scores has. So just a stat really.

I'm going to add Elena Temple DE to the site - and I'll remove that free version of Lost Lands.

#52 was an idea to include the titles in a bundle, though if I remove all of the bundles anyway, that won't be needed.

**Comment by benbarden** [comment]
Don't think there's anything else to do here - I'll close this.
