### ISSUE TITLE
Store game collection status changes in an activity log

### ISSUE THREAD

**Issue by benbarden** [benbarden/switchscores#105]
Each time someone adds an item to their collection, marks it as in progress, or marks it as completed, we should store this in an activity log.

The log would then be easy to display on the Community page, to show who's playing what.

Relates to #32 (quick status changes) but can be done independently.

**Comment by cosmo0** [comment]
Important point: the user should be able to keep this information private.

**Comment by benbarden** [comment]
Good point - there are a few things I can do to make this easier:

1. Have an on/off switch so each user can hide or show their activity. At any time, you'd be able to change this, and it would affect all of your history. (I don't think it's worth doing a per-item privacy setting)
2. As the activity log doesn't exist yet, it will start off empty - it won't start displaying historical items from the moment the change goes live.
3. It will default to OFF but I'll put an alert on the member dashboard and the games collection pages to say that you can make the activity visible if you want.
