### ISSUE TITLE
Series page counts non-listed games

### ISSUE THREAD

**Issue by cosmo0** [benbarden/switchscores#108]
"Games by series" page:

![image](https://user-images.githubusercontent.com/3973850/122028996-d37ae080-cdcc-11eb-9cf3-bf529fc55070.png)

In the series page:

![image](https://user-images.githubusercontent.com/3973850/122029092-e68db080-cdcc-11eb-8bbf-38702595fce0.png)

There's an episode that's not marked as available yet, but it's counted in the series' page.

**Comment by benbarden** [comment]
I'm thinking the best fix would be to show upcoming games on the series page?

**Comment by cosmo0** [comment]
Yeah, probably, that's a relevant information for users.

**Comment by benbarden** [comment]
I looked at this and Animus isn't a series anymore, is that now deleted?

I think the issue was because one of the games was de-listed. Upcoming games do get shown. This should be fairly rare but I can display de-listed games on the page.

**Comment by cosmo0** [comment]
Yeah since the "series" page was getting pretty huge, I've deleted a bunch of series that nobody cares about, or with only low-quality games. It's not a big deal.
