### ISSUE TITLE
Page to list mismatched publishers

### ISSUE THREAD

**Issue by cosmo0** [benbarden/switchscores#110]
It's not rare that a game changes publisher during its lifetime, whether deals change or a publisher or developer is bought by another. I'm in the process of assigning websites and Twitter IDs to publishers, and I find quite a lot of games with changed publishers.

I'd love a page listing the games where the publisher in SwitchScore DB does not match the publisher in Nintendo API. Sometimes it's normal (like a typo in Nintendo API or a shortened name) but sometimes it should be updated, and I'd like a way to check for that.

**Comment by benbarden** [comment]
Is this page sufficient? https://www.switchscores.com/staff/data-sources/differences/nintendo-co-uk/publishers
