### ISSUE TITLE
Add "other names" fields in game companies

### ISSUE THREAD

**Issue by cosmo0** [benbarden/switchscores#111]
Lots of companies change name or have multiple names.

Like NIS = Nippon Ichi Software, Playdius changed name for Plug In Digital (many other examples, but it's the one I just saw), etc.

It would be nice to have a "other names" field (with multiple entries), to trim down the "differences" page ( https://www.switchscores.com/staff/data-sources/differences/nintendo-co-uk/publishers )

It could also be displayed on the company's public profile. Did you know that you're the top search result for some publishers that don't have a website?

**Comment by benbarden** [comment]
Is it just for helping with the "differences" page, and to display the alternative names on the profile?

I see a few publishers in the Google Search Console, but there probably aren't that many searches for them. The only ones that have registered recently are: Artifex Mundi (this one comes up a lot), and Sabec (lol). Other searches are mostly for Top 100 Switch games (with lots of variations) and various game names.

**Comment by cosmo0** [comment]
Yes, it would be just for these. Maybe it could have another use, but mainly these.

I don't know what search results you get, but SwitchScore is in the top results when they don't have a website. I'm currently setting their websites/Twitter ( https://www.switchscores.com/staff/partners/games-company/without-website-urls ) : all the ones that have > 5 games as publisher don't have a website, and unless they have a generic name (like Digital Game Group) you're the best resource there is lol.

**Comment by cosmo0** [comment]
Also when I check "games without publisher" it would help to remember that (for instance) "Sometimes You" and "Evgeniy Kolpakov" are the same company. Because some publishers list their games under different labels but their contact informations are the same...

**Comment by benbarden** [comment]
This is a good idea that I'd still like to do (I know it's been a while). I'm moving most ideas to a separate backlog so will close this.
