### ISSUE TITLE
Category titles wrong if category contains "game"

### ISSUE THREAD

**Issue by benbarden** [benbarden/switchscores#112]
Two examples of this:

https://www.switchscores.com/games/by-category/card-game
"Nintendo Switch Card game games"

https://www.switchscores.com/games/by-category/word-game
"Nintendo Switch Word game games"

I can tweak this so it puts "Card games" and "Word games" for these two.

**Comment by cosmo0** [comment]
Yeah, maybe if the category ends with "game" you just put an "s" at the end?

**Comment by benbarden** [comment]
Fixed.
