### ISSUE TITLE
Feature suggestion: companies pages

### ISSUE THREAD

**Issue by cosmo0** [benbarden/switchscores#118]
- There is no company (publisher/developer) list. Maybe add a searchable list?
- In a company page (and the list above), it would be great to have the mean score of the company's games. To see if they tend to publish/develop good games.

**Comment by benbarden** [comment]
These are good ideas, I'll have a think about how best to incorporate them into the site.

**Comment by benbarden** [comment]
Not exactly what you suggested, but I've redesigned the page here:
https://www.switchscores.com/partners/games-companies

**Comment by benbarden** [comment]
Moving to separate backlog
