### ISSUE TITLE
Suggestion: improve games collection

### ISSUE THREAD

**Issue by cosmo0** [benbarden/switchscores#12]
In a game's page ( https://www.switchscores.com/games/5085/dicey-dungeons ):

- add a infobox/block "collection" on the right
- link "add to collection" redirecting to "add to collection" page ( https://www.switchscores.com/user/collection/add ) with the game pre-selected
- display the number of people who have this game in their collection

**Comment by benbarden** [comment]
I've done the first two. I've also added the user collection box when you're signed in.

Showing how many people have the game in their collection is probably not worth doing yet, as we don't have a lot of people registered and using the collection at this point.
