### ISSUE TITLE
Tags not appearing on the game's public page

### ISSUE THREAD

**Issue by cosmo0** [benbarden/switchscores#121]
https://www.switchscores.com/games/6679/dusk : no tag appear

![image](https://user-images.githubusercontent.com/3973850/139409832-6cfe3747-037f-46dc-b332-c734fdfce7cf.png)

https://www.switchscores.com/staff/games/detail/6679 : it has tags

![image](https://user-images.githubusercontent.com/3973850/139409880-5bcb80c9-a9f4-4783-b8d5-cb74284f827c.png)

**Comment by benbarden** [comment]
Ok, I've fixed this.
