### ISSUE TITLE
Suggestion: wishlists

### ISSUE THREAD

**Issue by cosmo0** [benbarden/switchscores#13]
Add a new user collection type "wishlist" (it could be a field in the collection table).

- Related to #12 : in the game's page, add a "add to wishlist" button
- In the game's page, display the number of people who have wishlisted it
- In the member dashboard: add a "view wishlist" button
- List games in the wishlist: category, score, price, if it's on sale or not

Bonus: send a mail when a wishlisted game is on sale, but sending mails is a nightmare. It could use a simple free service like Mailchimp or Mailjet.

**Comment by cosmo0** [comment]
Thinking about it, I think it'd be even better if people could create custom lists. Here's a breakdown:

- in the member dashboard, allow people to create lists of their own, with a title and description
- in the game pages, add a "list" block, with checkboxes for the user's list to add the game in one or several of them, and a text field to create a new one easily
- for all users (existing and new), create a default list "wishlist"
- allow users to make a list public, so they can share it

I'm sure people sharing their lists would bring more people on the site. This could also solve #26 because anyone could create a "looks interesting" list and share it.

**Comment by benbarden** [comment]
I had lists on the site before, but removed them as they weren't being used. I wasn't happy with the implementation either, so I'd do them differently if I did them again.

It is hard to compete with dedicated sites like The Backloggery though. A lot of people just use a spreadsheet. I think starting with specific list ideas might be worth a try - so, wishlists, or the looks interesting list. Custom lists are possible, it's harder to make them more compelling/worthwhile without putting lots of buttons or a long dropdown on the page.

**Comment by cosmo0** [comment]
After consideration, I'm not sure it's worth the trouble since Nintendo has a nice "add to wishlist" button in the store page. I'm closing this.
