### ISSUE TITLE
Games with broken eshop link and without publishers not appearing in "missing publisher" list

### ISSUE THREAD

**Issue by cosmo0** [benbarden/switchscores#136]
The game: [Pixel Game Maker Baggerman](https://www.switchscores.com/staff/games/detail/7025) doesn't have a publisher.

But it doesn't appear in the "[games with missing publishers](https://www.switchscores.com/staff/partners/data-cleanup/games-with-missing-publisher)" list:

<img width="1161" alt="Capture d’écran 2021-12-19 à 15 01 16" src="https://user-images.githubusercontent.com/3973850/146677591-a3335af1-73a0-4288-bf4e-4af41a454292.png">

It looks like all games with a broken eshop link don't appear in the "missing publisher" list:

<img width="1165" alt="Capture d’écran 2021-12-19 à 15 03 04" src="https://user-images.githubusercontent.com/3973850/146677648-b95b52a9-da4d-477a-a965-e1c700b1625a.png">

**Comment by benbarden** [comment]
This is because I tried excluding delisted games, but I don't think it worked properly. It should work better now.
