### ISSUE TITLE
Display bug in search when a game doesn't have an image

### ISSUE THREAD

**Issue by cosmo0** [benbarden/switchscores#14]
Search for a game that doesn't have an image:

![image](https://user-images.githubusercontent.com/3973850/104429658-29c9c600-5586-11eb-8d89-02c7e21c57fc.png)

**Comment by benbarden** [comment]
I need to make a new image to solve this - it shouldn't say WOS. Also, the images are stretched out when you search on mobile.

**Comment by benbarden** [comment]
I've changed the layout to use tiles rather than a table, which fixes the issue.
