### ISSUE TITLE
Download the header image when the eshop URL is filled but API link is broken

### ISSUE THREAD

**Issue by cosmo0** [benbarden/switchscores#140]

**Comment by benbarden** [comment]
Info on what we need:

Example game:
https://www.nintendo.co.uk/Games/Nintendo-Switch-download-software/FAR-Changing-Tides-2018248.html#Overview

Header image:
https://fs-prod-cdn.nintendo-europe.com/media/images/10_share_images/games_15/nintendo_switch_download_software_1/H2x1_NSwitchDS_FarChangingTides_image1280w.jpg

Square image:
https://fs-prod-cdn.nintendo-europe.com/media/images/11_square_images/games_18/nintendo_switch_download_software/SQ_NSwitchDS_FarChangingTides.jpg

The header image can be found here:
`<meta property="og:image"`

The square image can be found here:
`

<vc-price-box-standard id="price-box-standard-content" data-vue="vc-price-box-standard"
--
  | :context="'content'"
  | :layout="'game'"
  | :show-purchase-content="true"
  | :packshot-src="'https://fs-prod-cdn.nintendo-europe.com/media/images/11_square_images/games_18/nintendo_switch_download_software/SQ_NSwitchDS_FarChangingTides.jpg'"
  | :packshot-res="'high'">
  | </vc-price-box-standard>

`

**Comment by cosmo0** [comment]
You also often can rebuild the image URLs from the website page URL, without opening it.

Example with a download-only title:

> //www.nintendo.co.uk/Games/Nintendo-Switch-download-software/**([\w\-]+)**-[\d]+.html

Then you remove the "-" in the title, and the images become:

> //fs-prod-cdn.nintendo-europe.com/media/images/10_share_images/games_15/nintendo_switch_download_software_1/H2x1_NSwitchDS_{$GameTitle}_image1280w.jpg
> //fs-prod-cdn.nintendo-europe.com/media/images/10_share_images/games_15/nintendo_switch_4/H2x1_NSwitch_{$GameTitle}_image1600w.jpg

For physical games:

> //www.nintendo.co.uk/Games/Nintendo-Switch-games/**([\w\-]+)**-[\d]+.html

And it becomes:

> //fs-prod-cdn.nintendo-europe.com/media/images/10_share_images/games_15/nintendo_switch_4/H2x1_NSwitch_{$GameTitle}_image1600w.jpg

The only unknown is the casing: see Assassin's Creed Ezio Collection, which is all-caps in the product page URL but has Pascal Case in the image URL.

**Comment by benbarden** [comment]
I think it'll be more reliable to grab it from the page data rather than relying on a pattern - as I don't trust that the patterns will be used consistently for all games.

I've made some progress on this - will be pushing up some changes shortly.

**Comment by benbarden** [comment]
Criteria for which games can have their packshots downloaded via this method:

- Games must have a store override URL set.
- Games must not be linked to an item in the API. Broken links will not be included, but missing links (no link to the API at all) will be included. We can easily break the link if need be.
- Games must have no values set for image_square and image_header. This is to avoid continually re-downloading the same images. We can force it to re-run by blanking out those fields when editing a game.

I am running this in small batches and will post the affected games below, along with any where the store override URL needs fixing.

Fixed so far:
https://www.switchscores.com/games/2716/wolfenstein-youngblood
https://www.switchscores.com/games/2727/the-drama-queen-murder
https://www.switchscores.com/games/5093/super-meat-boy-forever
https://www.switchscores.com/games/5825/karma-incarnation-1

Not fixed - store URL is incorrect:
https://www.switchscores.com/games/3711/one-finger-death-punch-2

**Comment by cosmo0** [comment]
One Finger Death Punch: it's one of those rare games released in the US but not EU.

Shogi Battle Online: URL fixed

**Comment by cosmo0** [comment]
Is the "physical box art as square image" voluntary? It looks a bit weird.

<img width="577" alt="Capture d’écran 2022-03-11 à 21 50 36" src="https://user-images.githubusercontent.com/3973850/157962335-a0ad6ff5-5a38-44d9-a710-d1da4d99ddd7.png">

**Comment by benbarden** [comment]
Unfortunately it's either that image, the header image, or no image. This appears to be a side effect of scraping instead of using the API. I couldn't find any square images for the games with the physical images.

I could work around the issue by swapping these images for header images. Having the ability to use square images in certain parts of the site is useful though so it would be a shame to not be able to use those anymore.

**Comment by cosmo0** [comment]
The square image appears in the search results. You can rebuild its URL from the packshot URL.

Packshot:
> //fs-prod-cdn.nintendo-europe.com/media/images/05_packshots/games_13/nintendo_switch_8/PS_NSwitch_UndernautsLabyrinthOfYomi_PEGI.jpg

Square:
> //fs-prod-cdn.nintendo-europe.com/media/images/11_square_images/games_18/nintendo_switch_5/SQ_NSwitch_UndernautsLabyrinthOfYomi_image500w.jpg
