### ISSUE TITLE
Hot Wheels has a "pending" score marked as 0

### ISSUE THREAD

**Issue by cosmo0** [benbarden/switchscores#143]
https://www.switchscores.com/games/6491/hot-wheels-unleashed

The NWR score is 0, but their article says "pending". Given that the game has been released several months ago, I think it's fair to believe they will not update their rating.

The problem is that this "0" completely tanks the average score, making it look like a mediocre game, while it actually sounds pretty decent.

**Comment by benbarden** [comment]
Ah yes. There's another game with the same issue. It's because the scraper uses this page, and the score is blank:
http://www.nintendoworldreport.com/review/

I'll need to add a rule to fix this. Not much point deleting the review yet as it'll be imported again.

**Comment by benbarden** [comment]
This is fixed. It affected the following games:

https://www.switchscores.com/games/6491/hot-wheels-unleashed
https://www.switchscores.com/games/7354/chocobo-gp
https://www.switchscores.com/games/6927/ruined-king-a-league-of-legends-story
https://www.switchscores.com/games/5894/cris-tales
