### ISSUE TITLE
Link to the US eShop

### ISSUE THREAD

**Issue by cosmo0** [benbarden/switchscores#15]
A few games have been delisted from the EU eShop but are still in the US eShop (and a few have never been in the EU eShop, like Plunge).

-> add a link to the US eShop in the game's page, ideally with the US price

(I know it's a very hard and complex task but I'm writing down every idea I have)

**Comment by benbarden** [comment]
Yeah, this is a big one. I did have a go at it but didn't get very far...

**Comment by benbarden** [comment]
I don't think this is going to happen. The changes to scrape store pages via a URL and also the square packshot override should solve the issue of missing data.
