### ISSUE TITLE
Fix Youtu.be video links

### ISSUE THREAD

**Issue by cosmo0** [benbarden/switchscores#158]
### The problem 

Sometimes I do data entry from my phone. It's not easy but it works.

However, the "search video" link redirects me to the YouTube app, and when I copy the link to the video, it's a youtu.be shortened link.

And then, the video doesn't work when integrated in the game's page: https://www.switchscores.com/games/9596/space-haters

### The solution

- fix the existing links in the DB (a simple search and replace should do)
- when entering data, automatically change youtu.be links url to a YouTube.com link

**Comment by benbarden** [comment]
Moving to separate backlog

**Comment by benbarden** [comment]
I've fixed this. No data changes required. If you use a youtu.be link, the site will transform it so the video embeds properly.
