### ISSUE TITLE
Link to Steam & reviews

### ISSUE THREAD

**Issue by cosmo0** [benbarden/switchscores#16]
Quite a lot of games are in Steam and have reviews, but have no review for Switch. There are even "very positive" Steam games that have zero reviews on Switch, so people are missing out great games.

- Link Steam and Switch games (I'm sure @larsiusprime can help with a script)
- In the game's page (ex: https://www.switchscores.com/games/953/firewatch ), add a link to the Steam page (ex: https://store.steampowered.com/app/383870/Firewatch/ ) and the review summary ("very positive")
- In the search page (see #10 ) add a field to search by Steam review (very positive/mostly positive/etc)

**Comment by benbarden** [comment]
This is a really good idea, if we can find a way to link things up.

I think the search field is something to look at later. Need to get the data in the DB first!

**Comment by benbarden** [comment]
I've been thinking about how Steam could help with a lot of the unranked games on the site that are available elsewhere. Here's what I've found so far.

Example of an unranked game from 2017 - Koi:
https://www.switchscores.com/games/261/koi

Koi on Steam:
https://store.steampowered.com/app/1001070/Koi/

Once we have the Steam game ID (the "app ID") we can get some info from here:
https://store.steampowered.com/appreviews/1001070?json=1

Docs:
https://partner.steamgames.com/doc/store/getreviews

The query_summary at the top is pretty useful. We could also reuse the ranking algorithm from SteamDB:
https://steamdb.info/blog/steamdb-rating/

i.e.
`function GetRating( $positiveVotes, $negativeVotes ) {
    $totalVotes = $positiveVotes + $negativeVotes;
    $average = $positiveVotes / $totalVotes;
    $score = $average - ( $average - 0.5 ) * 2 ** -log10( $totalVotes + 1 );

    return $score * 100;
}`

If I add some code to handle this, and add a field for the Steam app ID, we could fill it in for a few games and see what it looks like.

I'll need to be careful to not load the info from Steam too often. Some ways to tackle this:

- start with a one-time update to get Steam info loaded for the first time
- games that have been released on Switch recently could be updated maybe once per week
- games that are older could be updated once per month at the most
- plus a button in Staff to manually request an update to a game

We can have some stats to keep track of how many games are on Steam, those that aren't, and those we've not checked yet.

It won't mean that games are "ranked" on Switch Scores - but it will be helpful for unranked games.

What do you think?

**Comment by cosmo0** [comment]
This all sounds really interesting, but I will definitely not manually link every game ^^

**Comment by benbarden** [comment]
I can do some. I don't think we need to link them all anyway - I was going to start with the unranked games first.

**Comment by benbarden** [comment]
Moving to separate backlog
