### ISSUE TITLE
Categories suggestions

### ISSUE THREAD

**Issue by cosmo0** [benbarden/switchscores#17]
# Categories changes

Rename "match-3" to "matching puzzle" to add all Puzzle Bobble-like, 2048 clones, and other matching puzzles that are not strictly "match-3".

Create "brick breaking" under arcade.

"Simulation" feels like a hodgepodge of many different things that are not related. I suggest the following sub-categories :
- rename "building and construction" to "Construction simulator" (for Bridge Constructor, Construction simulator...)
- create "Repair simulation" (for Car Mechanic Simulator & similar games)
- create "Physics simulation" (for all the weird physics-based games like Goat Simulator, Mugsters, Manual Samuel, Pizza Parking, Safety First, Godly Corp, Human Rocket Perso, Adventure of 00 Dilly...) and Angry Birds clones
- create "Life simulation" (for Ciel Fledge, Princess Maker, Sparkle, My Universe...)
- create "city building" for games like Cities Skyline & similar

Then I would move games around. That's a lot of sub-categories, but I think it would help a lot to have less of a mess.

# Ideas/not sure

I think it's missing an "action platformer" category for games like Ninja Gaiden. Not sure the split is necessary, though.

I feel want to create a "adventure-platformer" sub-category but I'm not sure it's a good idea (or what the name should be). There are a bunch of games that straddle the line between platformer, adventure, action, puzzle, and sometimes RPG. Maybe they're just "action-adventure" ? But it is often associated with 3D or Zelda-like games.  
Examples : classics like Prince of Persia/Flashback/Another World, Forgotton Anne, The Final Station, The Fall, The Way Remastered...

**Comment by benbarden** [comment]
- renamed Match-3 to Matching puzzle
- added Brick breaking
- renamed Building and construction to Construction simulator
- added Repair simulator - I've gone with simulator for all of these, rather than simulation, so it's consistent
- added Physics simulator
- added Life simulator
- added City building

I've not changed the others yet. Any further thoughts on those?

**Comment by cosmo0** [comment]
Thanks! I've submitted games for the new categories.

For the others, I'm still not sure. What do you think?

I would also like to create an "interactive story" under "adventure" for gameplay-light games (walking simulators, FMV, etc) but I'm not sure either that the split is really important.

**Comment by benbarden** [comment]
I don't have a strong view. How about leaving it for now (and closing this issue), and raising a new issue if you think it should be reconsidered?

**Comment by cosmo0** [comment]
Ok no problem. I think there are more useful issues anyway.
