### ISSUE TITLE
Series suggestions

### ISSUE THREAD

**Issue by cosmo0** [benbarden/switchscores#18]
List of games series (or licenses) that have more than 2 games and/or look like they would interest people.

I hope games can be in multiples series: Smash Bros could be considered to be part of a lot of series, for instance ; Puyo Puyo Tetris is both in Puyo Puyo and Tetris ; Sega Ages Sonic is both in Sonic and Sega Ages ; etc.

- Art of Fighting
- Asdivine
- Asterix & Obelix
- Bioshock
- Bloodstained
- Burger Time
- Contra
- Darksiders
- DC Comics (ex: Batman TellTale, Lego DC Super Villains, DC Universe Online...)
- Deponia
- Desktop Sports (Desktop Soccer, Desktop Volleyball...)
- Devil May Cry
- Disgaea
- Dragon Ball
- Dungeons & Dragons
- FIFA
- Fatal Fury
- Five Nights At Freddy's
- Football Manager
- Gradius
- Grisaia Phantom Trigger
- Gunvolt
- Jackbox Party Jack
- Just Dance
- Let's Sing
- Mega Man
- Mercenaries (ex: Mercenaries Saga, Mercenaries Wings...)
- Metal Slug
- Minecraft
- MotoGP
- My Universe
- NBA 2K (including Playgrounds)
- Naruto (rename "Naruto Shippuden" as there is one non-Shippuden Naruto game)
- No More Heroes (including Travis Strikes Again)
- Oddworld
- One Piece
- Pen & Paper (Knights/Galaxy of Pen & Paper)
- Puyo Puyo
- RBI Baseball
- River City/Kunio Kun
- SaGa
- Samurai Shodown
- Secret Files
- Shantae
- Sniper Elite
- Sparkle
- Sports Blast (Tennis Blast, Volley Blast...)
- Star Wars
- SteamWorld
- Steins;Gate
- Story of Seasons
- Syberia
- The Banner Saga
- The King of Fighters
- The Walking Dead
- TouHou
- Trine
- Warhammer
- Wonder Boy
- World Heroes

**Comment by benbarden** [comment]
Series is like category - only one per game. I will come back to this when we have the new section for suggesting series changes under Database help.

**Comment by cosmo0** [comment]
Too bad if it's only one series per game. Can't you change it before we start to work on it? I think many games would benefit by being in two (or more) series, especially retro games (Arcade Archives, Aca NeoGeo, Sega Ages...) and various crossovers or games with dual licences (Lego Star Wars...).

**Comment by benbarden** [comment]
It's possible, but it's a pretty big job.

**Comment by cosmo0** [comment]
Yes I assume so, but I think it might be worth it.

Or you can keep it like that, we do what we can with a single series, and migrate later, if ever.

**Comment by benbarden** [comment]
How many are in multiple series? If you leave out Arcade Archives, ACA NeoGeo, and Sega Ages? Perhaps series could be more of a character thing like Mario, Sonic, and things like Sega Ages could be more of a collection. That might help.

**Comment by cosmo0** [comment]
Collection, as in a new field? I like that idea. There aren't that many, though: besides these 3, there's Johnny Turbo's Arcade, maybe Konami Anniversary (only Contra, Castlevania and Arcade, for now) ?

Multi-series games:

- Double Dragon & Kunio Kun Bundle would be both Double Dragon and Kunio Kun ^^
- Fire Emblem Warriors would be both FE and Warriors, same for both Hyrule Warriors (Zelda and Warriors)
- Puyo Puyo Tetris (2 of them now) in both Puyo Puyo and Tetris
- All King of Fighters games mix Art of Fighting and Fatal Fury but it's not a big deal (we could do the opposite: list AoF and FF games as KoF)
- Smash Bros would be in pretty much all series lol

And apparently that's it? So not that many. Probably not worth to spend a few days on it, especially if you create another field for "collection".

**Comment by cosmo0** [comment]
@benbarden as a "series" I've written down "DC Comics" because there are two Telltale games, one "Lego DC Super Villains" and "DC universe online". Do you think it's a series? Or a collection? Or neither? I'm of the opinion that "Lego" is a collection because it regroups several series. What do you think?

**Comment by benbarden** [comment]
Hmm ... I don't think there's a perfect solution. Having Lego as a collection works for me.

**Comment by cosmo0** [comment]
Ok so I'll create DC Comics as a series

**Comment by cosmo0** [comment]
Everything's created, waiting for #55 to be completed to finish assignments

**Comment by benbarden** [comment]
@cosmo0 - Hey! Can you move any changes that require collections to #55 so we can close this issue?

**Comment by cosmo0** [comment]
ok
