### ISSUE TITLE
API for browser extension

### ISSUE THREAD

**Issue by cosmo0** [benbarden/switchscores#19]
I want to create a browser extension that, when looking at a page on Nintendo's site, displays some informations from SwitchScores.

For that I need an API to which I would send a Nintendo URL (from any Nintendo EU site: UK, FR, DE, ES...) and get back the following infos:

- url of associated SwitchScore page
- score and associated color, if any
- number of reviews
- category, and associated link
- rank (all time, year, category)
- tags, and associated links
- series, and associated links

**Comment by cosmo0** [comment]
@benbarden you once told me you already had a few API methods, but I can't find them. Could you refresh my mind? :)

**Comment by cosmo0** [comment]
For the plugin I have in mind, I would need the following.

A URL that takes a "Link ID" parameter, like: `/api/game/linkid/1173609`

The results should look like the following:

````json
{
  "SwitchScoreUrl": "https://www.switchscores.com/games/1/the-legend-of-zelda-breath-of-the-wild",
  "Category": "Action-Adventure",
  "CategoryUrl": "https://www.switchscores.com/games/by-category/action-adventure",
  "Series": "The Legend of Zelda",
  "SeriesUrl": "https://www.switchscores.com/games/by-series/the-legend-of-zelda",
  "Tags": [ "Open World" ],
  "AmazonUrl": "http://amzn.to/2w9HQTV",
  "Rank": "1/2480",
  "Score": 9.79,
  "Reviews": 16,
  "Color": "green"
}
````

Ideally, I could enrich search result pages: `/api/game/linkid?multiple=1,2,3

````json
[
  {
    "LinkId": 1,
    "Color": "red",
    "Score": 5.5
  },
  {
    "LinkId": 2,
    "Color": "orange",
    "Score": 7.2
  },
  {
    "LinkId": 3,
    "Color": "green",
    "Score": 8.6
  }
]
````

**Comment by cosmo0** [comment]
Here's a sample extension: https://github.com/cosmo0/switchscores-extension

It works the other way (adds Nintendo infos in the SwitchScore page), but it demonstrates content injection:

![image](https://user-images.githubusercontent.com/3973850/106609696-2793cf80-6566-11eb-85dd-55892957ae3b.png)

**Comment by benbarden** [comment]
Here you go - https://www.switchscores.com/api/game/linkid/1173609

**Comment by cosmo0** [comment]
AWESOME thank you!

Would you be able to do the multi-results one? With a limit of 25 (the number of results per page in a Nintendo EU search).

**Comment by benbarden** [comment]
That one might be better with a POST parameter so you can send an array. Maybe /api/game/linkid-batch/ and you could send ['linkids': '1,2,3,4,5,6'] in POST.

**Comment by cosmo0** [comment]
First draft

![image](https://user-images.githubusercontent.com/3973850/107630619-10d73200-6c64-11eb-81d3-ed680ca6a3ce.png)

**Comment by cosmo0** [comment]
The first draft of the extension has been approved by Firefox and is awaiting approval for Google and Edge stores.

https://addons.mozilla.org/fr/firefox/addon/switch-scores/

**Comment by benbarden** [comment]
I have updated the API so you can send multiple parameters. You will now get an array of "game" entries instead of just one. For consistency, you'll still get an array if there's only one item.

Example: /api/game/linkid/1883227,1173609

The change isn't live yet - are you ok for me to release it?

**Comment by cosmo0** [comment]
Yeah you can release it, I haven't advertised the extension yet. I'll make an update when I have the time. Thank you very much !

**Comment by benbarden** [comment]
All done!

**Comment by cosmo0** [comment]
The multi-query only gets me 3 results?

Example: https://www.switchscores.com/api/game/linkid/1576884,1514327,1533129,1173609,267464,269050,283531,273289,283542,267475,266263,1026135,267486 only returns Link's Awakening, Cadence of Hyrule and Breath of the Wild.

There are a few non-Switch or unreleased games in there (if I search for the whole site it's pretty hard to filter in JS), maybe that creates a bug in the API?

**Comment by benbarden** [comment]
I'm pretty sure this is because the link IDs don't actually exist on the site. I ran a similar query against the database:

`SELECT * FROM games WHERE eshop_europe_fs_id IN (1576884,1514327,1533129,1173609,267464,269050,283531,273289,283542,267475,266263,1026135,267486);`

and I got 3 results.

The 6-digit IDs don't look right anyway. Running this to find out:

`SELECT MIN(eshop_europe_fs_id) FROM games;`

And that query returns 1025152.

1173609 is BotW
1514327 is Link's Awakening
1533129 is Cadence of Hyrule

Where are you getting the other IDs? Which games would you expect them to be?

**Comment by cosmo0** [comment]
Those are the search results from https://www.nintendo.co.uk/Search/Search-299117.html?q=zelda&f=147394-86 (actually the FR site but it has similar results).

I parse the list of links and extract the number at the end of the URL.

If I don't specify "Switch" I get a bunch of games from different platforms (probably the 6-digits ones), but the Switch games are not all returned.

Although I see that I probably have a problem on my side because some games are returned in the "all" tab but not in the "games" tab.

**Comment by benbarden** [comment]
You need to limit the search to Switch games. You're currently getting all Zelda games :)

**Comment by cosmo0** [comment]
Yes I know lol. I'm trying to make the extension work even when the user doesn't filter on Switch.

**Comment by cosmo0** [comment]
So my URL parsing was buggy. Now it works perfectly 😄 

I'll update the packages on the extensions stores (it can take a few days to validate)

**Comment by benbarden** [comment]
Glad it's not me :) So can we close this now?

**Comment by cosmo0** [comment]
Yep! Thank you!
