### ISSUE TITLE
Integrate new sites

### ISSUE THREAD

**Issue by cosmo0** [benbarden/switchscores#20]
French sites:

- https://www.switch-actu.fr/
- https://www.p-nintendo.com/
- https://generation-nintendo.com/
- https://www.nintendo-town.fr/

**Comment by benbarden** [comment]
@cosmo0 - maybe you could ask these sites if they would like to participate? And if so, can they provide an RSS feed of their Switch reviews? The feed should not contain reviews for other platforms; also it shouldn't contain other content such as news.

Make sure they are scoring games out of 5, 10, or 100.

**Comment by cosmo0** [comment]
ok I can ask :)

**Comment by benbarden** [comment]
@cosmo0 - Generation Nintendo is on the site. How about the others?

I wonder if this might be better as a discussion, as there might be more sites to add later.

**Comment by cosmo0** [comment]
Moved to #77
