### ISSUE TITLE
Database help - series suggestions

### ISSUE THREAD

**Issue by benbarden** [benbarden/switchscores#21]
#18 made me think that perhaps the next section under Database help could be a way to suggest a series for a game. It would require the series to already be in the database.

**Comment by cosmo0** [comment]
Yes I think it would be much easier to continue filling data with series rather than with tags.

**Comment by cosmo0** [comment]
The series have been filled. There aren't that many, maybe you could close this issue? I'm sure we can fill them as they come.

**Comment by benbarden** [comment]
Yes, that makes sense. Also, I created this before you had Staff access, and you've already done the changes :) One less thing to build!
