### ISSUE TITLE
Difference in count of games without categories

### ISSUE THREAD

**Issue by cosmo0** [benbarden/switchscores#22]
In the /user dashboard it says 64 games:

<img width="383" alt="Capture d’écran 2021-01-13 à 23 49 20" src="https://user-images.githubusercontent.com/3973850/104519704-2a9c3f80-55fa-11eb-8366-48b90748b2cf.png">

In the page listing the years it says 50 games:

<img width="439" alt="Capture d’écran 2021-01-13 à 23 49 28" src="https://user-images.githubusercontent.com/3973850/104519724-338d1100-55fa-11eb-900e-a5bab2391bf2.png">

Are there 14 games without release date maybe?

**Comment by benbarden** [comment]
Games without release dates sounds about right. I am seeing something similar in the admin screens.

I have a list of 16 games without release dates in admin. Perhaps as a workaround you could try adding categories to these. It might break when you submit if it tries to go back to the listing, as it will try to get the year from a blank date.

These look like games I added manually, or where they have disappeared from the API.

4975 | Arrog
4833 | No More Heroes 3
4650 | Woodsalt
4110 | Klaus
3866 | Cooking Mama: Cookstar
3844 | Car Trader Simulator
3711 | One Finger Death Punch 2
3710 | Puzzle and Dragons Gold
1837 | Dead or Alive Xtreme 3: Scarlet
1834 | 8-bit ADV Steins;Gate
1496 | Sword of the Guardian
1464 | Bloxiq
1300 | Super Rock Blasters!
1163 | Trax: Build it Race it
765 | Eternal Edge
226 | Resident Evil: Revelations Collection

**Comment by benbarden** [comment]
Klaus is a duplicate. I'll remove it.

**Comment by benbarden** [comment]
I'm going to remove Resident Evil: Revelations Collection, I don't think we need to keep it as the games are already available separately.

**Comment by cosmo0** [comment]
Hey I found a URL with a list of games without dates :) https://www.switchscores.com/user/database-help/games-without-categories/submit-game-category-suggestion

**Comment by cosmo0** [comment]
Ok all done

**Comment by benbarden** [comment]
I think that URL shouldn't be possible ... you can actually put anything in place of "submit-game-category-suggestion". Whoops. I'll log a new bug for that.

We could handle this a bit better in the dashboard, but probably fairly low priority as you just cleared these up 😁
