### ISSUE TITLE
Categories navigation improvement

### ISSUE THREAD

**Issue by cosmo0** [benbarden/switchscores#23]
Some categories have so many games ("puzzle" has more than 300 games...) that they're getting hard to browse.

Splitting in sub-categories could help but I'm not sure it would really solve the issue, and then a user would need to navigate in multiple sub-categories, that's not ideal either.

I'm not sure what should be done, maybe adding a "filter" block above the games list:

- filter by tags/series (when there will be data)
- minimum score
- sort by score (ranked only), by name (unranked only), by name (all)
- display modes: grid/table
- include sub-categories (more games are displayed but you don't need to back-and-forth)

**Comment by benbarden** [comment]
Even with filters, the page will still show all the games when you land on them. Some design/layout changes might help.

I quite like the current layouts, but I agree they don't work so well with lots of games. Perhaps the solution is to have two different layouts - grid/table as you suggest - but to use those styles automatically depending on the content.

For instance, each landing page shows highlights of games in that category, such as top rated, displayed in a grid.

Then there could also be index pages that list the games in an A-Z table, just for that category. We used to have an "All games" page with the entire list in a table - I had to remove that as it took ages to load! But it might work better if the lists are smaller.

**Comment by benbarden** [comment]
I've done a new version of the category pages:
https://www.switchscores.com/games/by-category/roguelike

**Comment by cosmo0** [comment]
I like the concept of the "snapshot" page with the three categories. Having the newest releases is a very good idea.

I'm looking at how Steam does the "categories" pages, like https://store.steampowered.com/tags/fr/Action/ ; the concept of having the "big guns" in a slider/carousel at the top, and various lists below in tabs is interesting.

The links to the sub-categories are way too small, I almost didn't see them.

I have a few thoughts about the "table" lists:

- I feel the text is too small
- the link only on the small icon is too small a target (why not the whole title, or even the whole line?)
- why does it open in a new tab?
- could you add color to the score?
- the "rank" column is weird, users might not understand why its not incremental
- the "rank" and "average rating" columns in the "unranked" list are useless

**Comment by benbarden** [comment]
Good feedback - thanks.

Have a look now. I've made changes for all of your comments, but I've kept "rank" and changed it to "site rank", which might help to make it a bit clearer.

**Comment by cosmo0** [comment]
Much better!

Although, seeing it, I think I preferred the thumbnails display, it was easier to browse when you didn't know what you were looking for. A list of names doesn't make me want to click, I need a catchy logo :) It gives at least a sense of the style of the game: medieval or S-F, cute or dark, etc.

**Comment by benbarden** [comment]
I like the thumbnails too, but on such a long list it's much harder to make the layout work. I can add the small square thumbnails to the table perhaps, similar to the search results page.

**Comment by benbarden** [comment]
Thumbnails are now in the tables.

**Comment by cosmo0** [comment]
Nice! I like it :)
