### ISSUE TITLE
Tags suggestions

### ISSUE THREAD

**Issue by cosmo0** [benbarden/switchscores#24]
# Tags suggestions

Based on gamedatacrunch's tags collection, and browsing the lists and trying to find useful tags. I obviously don't know every game so it has to be an incomplete list.

I'm trying to think of actually useful tags to limit their number. People like zombies games, so it's a tag, but do people care about "demons" games? I'm not sure.

I think having tag categories/groups would help a lot during tagging, like having nested lists with checkboxes.

I think you can remove: JRPG (too vague/complex), horror, roguelike & tower defence (they are well-defined category).

## Genres and sub-genres

Some categories could also be tags when there are multiple games that are "both X and Y".

- Interactive story
- FMV
- Text-based adventure
- Investigation
- Open world
- Puzzle
- Music
- Farming
- Shooting
- Strategy

## Gameplay

- Text-heavy
- Exploration
- Minimalist gameplay
- Bird-flying (Aery, AER, Dune Sea...)
- Mini games
- Hack & slash
- Beat'em up
- Bullet hell
- Boss rush
- Block pushing (Sokoban)
- Bomb laying (Bomberman)
- Chess
- Poker
- Drawing
- Crafting
- Digging
- Dodging (a bunch of games are based on this gimmick)
- Cooperative organization (Overcooked & clones)
- Numbers-based
- Physics-based
- Traffic management
- Combat racing (Mario Kart...)
- Drifting
- Figures/acrobatics/tricks (not sure how it's called: games where you do tricks to gain points like BMX, skateboard...)
- Dodging racing (Out Run...)
- Time attack (racing alone against the clock)
- Cards-based (more and more X games that integrate cards in their gameplay)
- Hunting
- Repair
- Search (Where's Wally-type: Hidden Through Time, Wind Peaks, Hidden Folks...)

## Setting

Only if distinct from "modern" which seems to be the default

- Science Fiction
- Heroic Fantasy
- Fantastic
- Antiquity Europe
- Medieval Europe
- Medieval/Edo-era Japan
- XIX/early XX century
- World War I
- World War II
- Nordic
- Eastern Europe
- Asian
- Underwater
- Space
- Dystopian
- Super Heroes
- Western

## Story

- Coming of age story
- Love story
- Family story
- Dating
- Political
- Time travel story
- Travel story

## Content

- Zombies
- Cats
- Dogs
- Cops
- Erotic
- Cthulhu
- Horses
- Dungeons
- Mecha/robots
- Dinosaurs
- Pirates
- Café/Restaurant
- Ninjas
- Motorbikes

## Mood

- Emotional
- Funny
- Sad
- Melancholy
- Scary
- Weird

## Multiplayer

- Local multiplayer (single console)
- Local multiplayer (multiple consoles)
- Online multiplayer

## Visual styles

- Voxel
- Pixel art
- Anime
- Minimalist visuals
- Low-poly
- Realistic
- Cartoon
- Black & white

## Viewpoint

- Isometric
- First-Person
- Third Person
- Top-Down
- Side Scroller

## Time

- Turn-based
- Real-time
- Real-time with pause

## Difficulty

- Hardcore
- Die & retry
- Old school difficulty
- Casual
- Relaxing
- No fail state
- Assists/accessibility options

## Audience

- Family friendly
- Kids friendly
- Mature/adults
- Young girls
- LGBT-friendly
- Gore
- Nudity

## Retrogaming

- 80's retrogaming
- 90's retrogaming
- 00's retrogaming

## Scoring

- Score-based
- Speedrunner-friendly

**Comment by benbarden** [comment]
This is really good stuff. I think it will definitely help with finding games on the site - there are over 4600 now.

It'll be a big job, especially the search part, which will be necessary so you can actually find the games. I could do that in PHP but it would be better in a proper search engine, which is a bit beyond my capabilities. I might have a go!

**Comment by cosmo0** [comment]
I'm not sure what you call a "proper search engine"? There's not that many entries in the DB, a simple query like `inner join game_tag [...] where tag_id IN (list,of,tags)` should do the trick?

**Comment by benbarden** [comment]
I mean tools such as Lucene, Solr, ElasticSearch rather than MySQL. It's possible to do it in MySQL, but the matching is much more limited.

If it's just a case of showing a list of tags and clicking on them to view the games, like we do with categories, that's pretty straightforward once tags are working. It gets more difficult when you need to combine several search criteria, such as free text, category, tag, and other filters.

**Comment by cosmo0** [comment]
I'm not sure such tools are very useful for such a small dataset, 4600 entries is a very small number. `Join`s for tags and categories should probably still be fast enough, and Mysql even has some sort of full-text search feature.

I'd say try to do something simple, and if it's too slow, only then think about using another tool, otherwise you risk spending a lot of time on it for very little gain.

**Comment by cosmo0** [comment]
I'm thinking of adding tags "must have" and "exclusive". What do you think?

**Comment by benbarden** [comment]
Exclusive could be really useful. One issue is when a game starts as an exclusive but then goes to other platforms. That happened with Super Bomberman R, for example. I think it's more of a field than a tag though.

I see what you're saying with Must have. Not quite sure what would be the best solution to that though...

**Comment by cosmo0** [comment]
After thinking about it, I think my idea of "top 50 games that are also in the top 50 in number of reviews" would fit. They're basically the best *and* most talked-about games, which would make them "must haves"?

**Comment by benbarden** [comment]
"in the top 50 in number of reviews" is the part I'm unclear on.

To give you an idea, if I exclude any games with 6 or fewer reviews (I just chose 6 as the cutoff to try it out), these games are left out of the top 100: (not sure how this will look in terms of formatting)

`
# id	title	game_rank	review_count
3449	Kentucky Route Zero: TV Edition	7	4
4641	9th Dawn III	12	3
2910	Divinity: Original Sin 2 - Definitive Edition	13	5
4703	Horace	17	6
623	Undertale	33	6
1420	Gone Home	33	3
3735	Children of Zodiarcs	33	3
4546	Moero Crystal H	33	4
5081	When the Past was Around	33	4
3557	Murder by Numbers	45	6
3109	Return of the Obra Dinn	50	5
3351	The Talos Principle: Deluxe Edition	50	5
5085	Dicey Dungeons	54	5
1478	TowerFall	59	3
4488	Mo:Astray	64	5
324	Deemo	73	4
1483	Into the Breach	73	6
3310	Assassin's Creed: The Rebel Collection	73	4
3938	Huntdown	73	6
665	The Banner Saga 3	87	5
1502	Forgotton Anne	87	5
8	Shovel Knight: Treasure Trove	93	6
434	Wandersong	93	6
3386	Nurse Love Addiction	93	3
3845	Yumeutsutsu Re:Master	93	3
`

**Comment by cosmo0** [comment]
I don't see many games that are really must-haves in this list.

Divinity 2 is very good but I rarely see anyone recommend it (and it's more a PC game). Assassin's Creed too, they're good games but getting old. Shovel Knight is a classic but not what I consider a "must have", it's still a retro indie.

The rest are indies, so it's not surprising they don't appear in a "must have" list. They're more "hidden gems", niche games, or "indie darlings".

What's the minimum number of reviews when you query the top 50 `order by review_count desc`? And then what do you get when you query the top 50 games `where review_count >= $reviews order by score desc` ? Just to see if the result has some sort of coherence.

**Comment by benbarden** [comment]
Sorry, I've not come back to this recently. I wonder if some of this might be better as a discussion? I think we're also talking about a few different ideas.

**Comment by cosmo0** [comment]
Agreed; I'll create a discussion about "must-haves". The rest doesn't seem to be as much a subject of discussion?

**Comment by benbarden** [comment]
@cosmo0 - Is there more of this issue that needs doing, maybe splitting into a few ideas or discussions? Or can we close it?

**Comment by cosmo0** [comment]
Would you do the tags categories?

Either way, I still have to create the tags, and then fill them. Could you delete the existing ones?

I would also appreciate an easier interface to add them:

- adding multiple tags at once on a game (list of checkboxes instead of a dropdown)
- being able to add games to a tag (from the tags page)

**Comment by benbarden** [comment]
I was trying to think how best to do this, and while I think the tag categories would be really useful, it could make the interface a lot more complicated. But I think I have a way to do this.

The multiplayer options are a separate thing really - see #76 .

**Comment by benbarden** [comment]
@cosmo0 - I've got a working version of this on the site. 🎉 

Quick overview:

- The tag categories you've suggested are available to use. All existing tags have been cleared.
- Go to https://www.switchscores.com/staff/categorisation/tag/list to create and edit tags.
- When creating tags you'll need to choose a category. I haven't provided a way to change the tag categories (they are not the same as game categories) - I don't think we'll need to add them very often. I can change them if needed.
- Once you've added some tags, go to the Detail page for any game and click Tags. Example - https://www.switchscores.com/staff/games/detail/5104
- You can now add lots of tags to a game in one go. You'll need to create some tags first.
- Once you've tagged some games, they will be linked from here - https://www.switchscores.com/games/by-tag

I haven't provided a way to add games to a tag from the tags page as that is a bit more work, but hopefully this is a good enough start. Let me know any feedback!

**Comment by cosmo0** [comment]
Really cool! Thanks! I'll try to fill a few games and let you know :)

**Comment by cosmo0** [comment]
@benbarden you've missed the "viewpoint" category

**Comment by cosmo0** [comment]
Also, could you sort the tags alphabetically inside the categories ? :)

**Comment by benbarden** [comment]
Added Viewpoint, and sorted the tags alphabetically. I also fixed a bug where & was being converted to &amp; when editing.
