### ISSUE TITLE
Feature idea: "looks interesting"

### ISSUE THREAD

**Issue by cosmo0** [benbarden/switchscores#26]
While categorizing the games, I've stumbled upon a bunch of unranked games that looked very interesting ; some even had glowing reviews on Steam but not a single one on Switch. Or sometimes they look like very weird games that have mixed reviews but could interest people who like weird games (I certainly do).

I'd love to help other people find these games. A button to mark them as "hey take a look", and a page that lists such games, with the number of people who marked it.

It's not exactly a whishlist because they would not necessarily be games that I am interested in right now, or at all.

Examples include:

- a weird "walker" shooting game: https://www.switchscores.com/games/3615/be-a-walker
- a cute but classic platformer: https://www.switchscores.com/games/4754/dadish
- a weird rhythm game: https://www.switchscores.com/games/4667/hide-dance
- an action arcade game: https://www.switchscores.com/games/4595/jet-set-knights
- a Mega Man clone that looks cool: https://www.switchscores.com/games/4520/firework
- a fighting game that looks bonkers: https://www.switchscores.com/games/3998/fly-punch-boom
- etc...

**Comment by benbarden** [comment]
This is an "interesting" idea :)

When people visit the site, I think it's good if people can see that it's active, useful, and provides interesting things they can't easily find elsewhere. This idea fits all of those categories nicely.

The main thing to think about is where to show the list of interesting games to people. Some possible ideas:

- right on the homepage - perhaps it is a better way of doing the random game idea. Members choose some interesting games, I approve them, and they go into a queue that rotates daily.
- on a new Community page - which could show other recent activity, such as recent reviews, recent games added to your collection etc. I've had ideas for a page like this for a while.
- somewhere else?!

What do you think? This is probably my favourite idea at the moment :)

**Comment by cosmo0** [comment]
Use it for a "random game" is a good idea. In a box "Find a new game" under "latest news" on the home page? Maybe a mix of "looks interesting" and highly-rated-but-low-number-of-reviews? (aka "hidden gems")

A community page is a good idea too. It would give users an incentive to register.

**Comment by benbarden** [comment]
Ok, I think putting this on the homepage would be a good reason to remove quick reviews from the homepage (for now), as they are not very up to date. Quick reviews will go on the Community page when that's ready.

**Comment by benbarden** [comment]
This is now live! To use it, go to the Members dashboard, and look for the new "Featured games" box. Try submitting a game. Once approved, it will appear in rotation on the homepage.

For now, the rotation is totally random, but in the future I might tweak that - particularly if the list gets very long. Think of it as a random game from a member-suggested, curated list - rather than a random game from the entire database.

**Comment by cosmo0** [comment]
Really cool! I'll take a spin :)

**Comment by cosmo0** [comment]
Maybe you should return on the "search" page when you submit :) https://www.switchscores.com/user/search-modular/add-featured-game

And add a button in the game's page ? And hide it if it's already selected, marking it like "is featured as [interesting|hidden gem]"

**Comment by cosmo0** [comment]
Idea for the options labels while adding a featured game:

- It is or looks interesting, unique or weird
- It is a hidden gem: I love it but nobody knows about it

And a sub-text like: "please don't add well-known games as hidden gems, everyone knows about Celeste, Hollow Knight and Undertale". Or even don't allow to submit "hidden gems" if the number of reviews is too high?

You could even create a third option "I love it despite its flaws and/or mixed/bad reviews". I have a huge fondness for a lot of games that are ranked very poorly.

Oh, and in the feature submit page, could you display the game image like in the category submit page please :)

**Comment by benbarden** [comment]
@cosmo0 can you add these comments to a new issue please? :) I'd like to be able to close issues when they are done - any further comments are harder to keep track of when the issue is closed. Otherwise these threads will go on forever, as there is always more that can be done ...

**Comment by cosmo0** [comment]
Done! Sorry :)
