### ISSUE TITLE
Missing image

### ISSUE THREAD

**Issue by cosmo0** [benbarden/switchscores#27]
Sonic Mania Plus has a missing image but no replacement:

<img width="633" alt="Capture d’écran 2021-01-17 à 00 54 13" src="https://user-images.githubusercontent.com/3973850/104827501-89fa8980-585e-11eb-8eaa-9f0dffc1f815.png">

**Comment by benbarden** [comment]
This isn't ideal, but I've copied the Sonic Mania image and linked that up so it's not empty.
