### ISSUE TITLE
Write API docs

### ISSUE THREAD

**Issue by benbarden** [benbarden/switchscores#28]
Relates to #19 .

**Comment by cosmo0** [comment]
Do you know Swagger?

**Comment by benbarden** [comment]
I've come across it but not used it for a few years. The main blocker to doing this is API authentication - there are a couple of endpoints I'd like to put behind a token/login. I think this is a fairly low priority for now.

**Comment by benbarden** [comment]
Will close this, I have a note of it but only 2 people are using the API, and docs haven't been needed so far.
