### ISSUE TITLE
Getting more people to register

### ISSUE THREAD

**Issue by cosmo0** [benbarden/switchscores#37]
In order to get users to register and create a community, several things could be improved.

Incentives to register: add messages like "register to do X" in as many places as possible. Register to add this game to your collection, register to add a quick review, register to help with the database...

Make the site more useable for international users: for instance, currently, the prices are displayed only in £, which is only useful for UK users. I think displaying the price in € and $ (and US sales) would help a bit, although not a lot. Displaying at least £ and € would be a huge improvement: € and $ prices are often the same (a 10€ game is 10$ in the US), but I have no idea how much a £ is worth.

Create unique features ; I really think my idea of a browser extension that inserts infos directly in the page (see #19) would be a game-changer for many people: a simple way to see if this "-90% game" is worth it. Although it's probably not easy, especially since ideally it would require to match the games to all EU stores and the US one, but I'm convinced it would be worth it.

Just talk more about the site. Get people to talk about it on Twitter, Facebook, Reddit, Resetera, whatever. It's also one of the more time consuming and less rewarding ways, especially since you don't gain money from visitors, but following a few forums and posting a useful link to the site once in a while might help.

Better SEO:
- meta description tags
- descriptions in categories ("Adventure games are..."): content is king in SEO, more relevant content = better SEO
- better titles: titles that match what people google, like "best X Switch games" as category list titles

**Comment by benbarden** [comment]
@cosmo0 we now have discussions! 🎉  Unfortunately, there isn't a way to convert this issue to a discussion - could you copy your comments and start a new discussion here?
https://github.com/benbarden/switchscores/discussions

**Comment by cosmo0** [comment]
I didn't even know Github had discussions lol.

Done: https://github.com/benbarden/switchscores/discussions/46
