### ISSUE TITLE
Allow users to set categories they like

### ISSUE THREAD

**Issue by benbarden** [benbarden/switchscores#41]
Split from #39 raised by @cosmo0 

Allow users to set their own category: I'm not a fan of puzzle games but I'm willing to play more shmups for instance.

Link to game page from list of games and display the category

**Comment by benbarden** [comment]
This doesn't work as well as you might expect, as campaigns are a fixed list of games rather than dynamic. If you filtered the list it would be very short.

Alternative options:
- dynamic campaigns - although then it's not really a campaign. I think of a campaign as something that has a set number of items in it and that will finish at some point. If it's dynamic, new games will keep being added, and it'll be an ongoing thing.
- working this into the unranked games list - there are a few lists of unranked games in the reviewers dashboard. This could be changed so you can see a list of all unranked games and filter by category. And that could go into the member dashboard, if it's useful.

**Comment by cosmo0** [comment]
I think the main problem with the campaigns as it stands (besides the fact that there aren't many users, haha) is that there are too many items in each, and it's both discouraging and hard to browse.

Having a shorter number of items (like 20) would be much more manageable, and you could advertise them on the front page: "come help us rate these games, look, there's only 10, how hard can it be?".

Splitting the campaigns could be useful, like "puzzles games released in 2020".

**Comment by benbarden** [comment]
@cosmo0 - Maybe this is more of a general change. If members can select the categories they like, this could be used for other things, not just campaigns. For example, we can show members the top games in the categories they like that they don't already have in their collection. That's similar to an idea I already built into the games collection recently, but it could work across multiple categories too.

**Comment by cosmo0** [comment]
I like that idea :)

**Comment by benbarden** [comment]
Moving to separate backlog
