### ISSUE TITLE
"Add a featured game" page modifications

### ISSUE THREAD

**Issue by cosmo0** [benbarden/switchscores#43]
Idea for the options labels while adding a featured game:

- It is or looks interesting, unique, weird, or caters to a very specific audience (ex: is extremely cute)
- It is a hidden gem: I love it but nobody knows about it

And a sub-text like: "please don't add well-known games as hidden gems, everyone knows about Celeste, Hollow Knight and Undertale". Or even don't allow to submit "hidden gems" if the number of reviews is too high? (update: after submitting a few games, I've noticed that some have a high number of reviews but are still totally unknown, so it's not a good solution)

You could even create a third option "I love it despite its flaws and/or mixed/bad reviews". I have a huge fondness for a lot of games that are ranked very poorly.

Oh, and in the feature submit page, could you display the game image like in the category submit page please :)

_Originally posted by @cosmo0 in https://github.com/benbarden/switchscores/issues/26#issuecomment-766242932_

**Comment by benbarden** [comment]
For the moment, the options don't do anything as they don't show up on the page. I'd like to change that first and then we can look at adding more / tweaking the text.

**Comment by benbarden** [comment]
Featured games aren't currently displayed on the site. I think if we want to bring them back, this feature may need to be looked at more broadly.
