### ISSUE TITLE
Change sub-labels for ranked/unranked

### ISSUE THREAD

**Issue by cosmo0** [benbarden/switchscores#45]
I like the new labels for ranked/unranked lists, but they're not uniform. What about "3 reviews or more" / "2 reviews or less" ?

_Originally posted by @cosmo0 in https://github.com/benbarden/switchscores/issues/9#issuecomment-766428620_

**Comment by benbarden** [comment]
Done - see here: https://www.switchscores.com/games/by-category/platformer-2d

I slightly reworded the text to "2 reviews or fewer" but otherwise, this is done.
