### ISSUE TITLE
Featured games: rotate a group monthly

### ISSUE THREAD

**Issue by benbarden** [benbarden/switchscores#48]
I took a bit of a shortcut with featured games: the entire list is random. All the games are curated (submitted via the Member dashboard), but as the list gets longer, there are probably too many games for it to be completely random.

I was planning to do it more like this:

- Each game is assigned to be the featured game for a day.
- If you visit the site on a day when there is a featured game set, you see that game all day - it doesn't randomise.
- If you visit the site on a day when there is no featured game set, you get a random game as you do now.

I could add some staff tools to make this easier than needing to set the date for each game individually:

- A button to automatically assign a date to every featured game, starting with today and continuing until there are no more featured games in the list.
- Automatically archive featured games for days in the past.
- A button to reuse previously featured games, and push them onto the end of the list.

This seems better than a fully random list, although it does technically work. So we end up with a "game of the day" instead.

Any thoughts @cosmo0 ?

**Comment by cosmo0** [comment]
I agree a "game of the day" sounds better than a refresh every time. Or a new game each hour/half day/whatever?

Manually picking a game sounds like a lot of work, and prone to mistakes and omissions.

Maybe a cron job could pick a random game id from the list and write it somewhere (text file/table)?

**Comment by benbarden** [comment]
Maybe I could simplify this a bit.

Instead of it being random from a big list (as it is now), or a game per day, how about if we have a group of games per month? So in April, we could have 20 or 30 games that are selected at random. Then in May, we have a different 20 or 30 games.

Would need a bit of curation, but probably a bit easier to manage.

**Comment by cosmo0** [comment]
That sounds like a good compromise :)

**Comment by benbarden** [comment]
I'm going to do this a different way, using the starred games from Switch Weekly - when I get a chance to build that.
