### ISSUE TITLE
Allow attachment of links to short reviews

### ISSUE THREAD

**Issue by cosmo0** [benbarden/switchscores#54]
Nindie Spotlight has stopped making full-length reviews and instead switched to making Let's Play and mini-reviews: https://www.nindiespotlight.com/2021/01/mini-reviews-january-28th-edition.html

Maybe they would be interested in copying their review as "quick review" on SwitchScore, provided they could link to their site or Youtube?

Maybe that feature would interest other youtubers?

**Comment by benbarden** [comment]
I have their reviews up to June 2019, when the mini reviews format started:
https://www.switchscores.com/reviews/site/nindie-spotlight

There are a few things to think about here:

- Including links in quick reviews is possible. Maybe they would then need to be called member reviews (I don't see much benefit in having a very short review that you have to go to another site to view). However I don't think it's needed to get the reviews from Nindie Spotlight on the site. Nindie Spotlight is already a partner, so those reviews could be included in the partner reviews.
- The bigger issue is that none of the mini reviews have scores. Older reviews have scores. Unfortunately when mini reviews started, the scores stopped.
- Nindie Spotlight might also not want to spend time adding their reviews manually to Switch Scores. I don't have an easy way to import them as they are now though.

**Comment by cosmo0** [comment]
Nindie Spotlight might be interested in copying their review and linking to the Youtube video (on which they make money).

The other issue with their mini reviews is that they are lumped in a single post.

Maybe we could get their opinion lol

**Comment by benbarden** [comment]
@cosmo0 - I think you talked to Nindie Spotlight and there didn't seem to be a clear way to link their reviews to scores. I don't think we should make a change here yet.

Perhaps if there's further comments we could continue as a discussion. Can we close this issue?

**Comment by cosmo0** [comment]
Above all they didn't want to have to score their reviews, linking their video wasn't the real issue.

So I'm closing this, yeah.
