### ISSUE TITLE
Collections

### ISSUE THREAD

**Issue by benbarden** [benbarden/switchscores#55]
Relates to #18 

Similar to series - but gives an additional dimension to categorise things by.

Collections to be used are things like ACA NeoGeo, Arcade Archives, Sega Ages.

**Comment by cosmo0** [comment]
Here is a list of collections that I see.

Transform the following series to collections:

- ACA NeoGeo
- Arcade Archives
- Johnny Turbo's Arcade
- Lego (has various series underneath like Batman and soon Star Wars)
- Sega Ages

New collections;

- Konami Anniversary ? only 3 games for now: Contra, Castlevania and Arcade but there are rumors of more
- Neo Geo Pocket ? a bunch of games released like King of Fighters R2, Samurai Shodown! 2, SNK Gal Fighters, with more coming

**Comment by benbarden** [comment]
I added one this morning (as a series) - G-Mode Archives.

The naming in the API is a bit weird - the game is called "G-MODE Archives29 ZANAC" - https://www.nintendo.co.uk/Games/Nintendo-Switch-download-software/G-MODE-Archives29-ZANAC-1909682.html

I think the series is as I've written it, the entry number is 29, and the game is called "Zanac". I never understand why some games in the API are written in capitals like that, and for this game it's weird that the 29 doesn't have a space before it. Anyway, I've tidied up the title a bit as you can see here:
https://www.switchscores.com/games/5292/g-mode-archives-29-zanac

**Comment by cosmo0** [comment]
Yeah it's a weird collection for weird games. They are games that released on Japanese flip-phones before smartphones existed, and are still in usage to this day.

Japanese eShop has much more "G-Mode" games, while we only have 2 that have been localized (Zanac and Topolon), which is why they are number 25 and 29. I'm not sure it warrants a series or collection yet, but maybe in the future they will.

Japanese games love to have weird names, see "void tRrLM(); //Void Terrarium" or "Is It Wrong to Try to Pick Up Girls in a Dungeon? Familia Myth Infinite Combate"

**Comment by cosmo0** [comment]
Collections to create (or convert from existing series):

- Arcade Archives
- ACA NeoGeo
- Sega Ages
- Johnny Turbo's Arcade
- Konami Anniversary
- NeoGeo Pocket
- Lego
- G-Mode Archives
- Capcom Legacy ? (Mega Man Legacy, Street Fighter Anniversary, Beat'em Up Bundle, Arcade Stadium...)
- Pixel Game Maker

**Comment by cosmo0** [comment]
Any update on this? :)

**Comment by benbarden** [comment]
Not yet but I'm hoping to do it very soon.

**Comment by benbarden** [comment]
This is now done. As part of the changes, I also migrated games to collections where I could find a match, and cleared the series for those games.

**Comment by cosmo0** [comment]
Nice! But I can't edit or delete (empty) series now :(

**Comment by benbarden** [comment]
That will be possible when I do #100 - I've been needing to do that anyway.

As collections are now done, I'll close this issue.
