### ISSUE TITLE
Suggestion: add more information in the "games by category" page

### ISSUE THREAD

**Issue by cosmo0** [benbarden/switchscores#6]
In the page: https://www.switchscores.com/games/by-category

Display the sub-categories directly under the main categories in a nested sub-list:

- Adventure
  - Action-adventure
  - Puzzle adventure
  - Visual novel
- Arcade
  - ...

Display the number of games in the category : "Adventure (261)"

**Comment by benbarden** [comment]
Great idea!

**Comment by benbarden** [comment]
Done!

**Comment by cosmo0** [comment]
Nice! 👍 
I'm not sure the difference in font size is necessary, though.
