### ISSUE TITLE
Game page: display video

### ISSUE THREAD

**Issue by cosmo0** [benbarden/switchscores#60]
I saw you have a "video" field that points to Youtube videos.

I could search and fill the trailers for the games, but they're not currently displayed.

Suggestion: add a "play" button on the header image like Nintendo does, that plays the trailer from Youtube in an embedded modal popup.

**Comment by benbarden** [comment]
Let me see what I can do.

**Comment by benbarden** [comment]
It's not perfect, but see what you think - https://www.switchscores.com/games/1/the-legend-of-zelda-breath-of-the-wild

**Comment by cosmo0** [comment]
Honestly, I think it's a bit weird.

I think using the same mechanism as the Nintendo site would be clearer for the users, who are probably used to how it works: a big "play" button semi-transparent overlay over the image.

If you don't like it centered it could be near a corner like that: https://codepen.io/cosmo0/pen/YzpXyjq

**Comment by benbarden** [comment]
I'll meet you halfway - I don't think it's great to just copy the Nintendo site. It's now a button with a modal. Try it out:

https://www.switchscores.com/games/1/the-legend-of-zelda-breath-of-the-wild

I've set it to pause the video when the modal is hidden. If you reopen it, it'll resume.

**Comment by cosmo0** [comment]
I still think it's a bit weird but it's much better.

What about a `<i class="fa fa-play"></i>` in the button?

And what about "watch trailer" or something similar, to specify that it's a trailer you're about to watch, not a playthrough?

**Comment by benbarden** [comment]
Have a look now.

**Comment by benbarden** [comment]
Thanks! I can do something to help...
