### ISSUE TITLE
Game format options: physical, digital, DLC, demo

### ISSUE THREAD

**Issue by benbarden** [benbarden/switchscores#61]
I think we should merge #58 and #59 into one idea: game format options, and add some other options too.

Each game could have the following options:

- Digital - Available/Limited edition/Not available/Not set
- Physical - Available/Limited edition/Not available/Not set
- DLC - Available/Not available/Not set
- Demo - Available/Not available/Not set

"Not set" would be the default, to show the games that haven't been updated yet.

I've included "Limited edition" as a lot of physical titles released through Super Rare Games or Limited Run Games won't be on Amazon, unless they are re-sold. I'm not sure if "Limited edition" is needed for Digital, but it would apply to Super Mario 35 and Super Mario 3D All-Stars.

DLC and Demo don't have to be added yet, but they will have similar options so it might be easier to add them at the same time.

Some of these might be available in the API - if so I can save some manual effort and write a script to do a mass-update.

Once these options have been added, they could all be displayed on game pages. And as you say in your original issues, I could make the following changes too:

- No price list to exclude games where Digital is Not available
- No Amazon link list to only show games where Physical is Available

**Comment by benbarden** [comment]
@cosmo0 let me know if this issue means we can close the other two.

**Comment by cosmo0** [comment]
Instead of "digital limited", I think it should rather be simply "removed" or something like that (I can't remember the proper word). Many digital-only games have been removed from the store for a reason or another.

I like the digital/physical multi-options :)

If DLCs are in the API I agree they could be added. Otherwise, I'm not sure it's interesting enough to spend a lot of time on it, especially since it often changes a long time after the release, DLCs can be removed/added... Some languages are added as free DLCs (like Witcher 3), some games variants have DLC included from another version (like "deluxe" versions)...

Demos can also be temporary: for instance, the Monster Hunter Rise demo will soon be removed (if it hasn't already). They also are often added a long time after the release: the demo for Immortals Fenyx Rising has been released recently despite the game being available for a few months.

**Comment by cosmo0** [comment]
Quick note: some games are only available physically in bundles. Like Resident Evil Revelations, or Cat Quest 2 (only available as a bundle with the first, which has its own physical release).

**Comment by benbarden** [comment]
For demos I mean when a released game (or a soon to be released game) has a demo available. I'm not including demos that are released separately from the main game. They aren't usually in the API anyway.

The options for physical and digital formats will be:

- Available - means you can get the game in physical or digital format. (one value per format)
- Included in bundle - this would be used if you can only get a game as part of a bundle. Cat Quest 2 could be "Available" for digital, and "Included in bundle" for physical.
- Limited edition - I see your point about not using this for digital, but I think this option is good for any physical titles released via Super Rare Games or Limited Run Games. I can make this option physical-only.
- Not available - if a game is not available in physical or digital format.
- Discontinued - my idea was to use this if a game was previously available in a format but not anymore. This might overlap with the De-listed field. Perhaps there aren't any games where one format is discontinued but the other isn't. I can add the option and see if it's useful? For physical games, I think we only need "Limited edition" and not "Discontinued" - as that would mean you might be able to find the game on eBay. That's different to it being removed from the eShop.
- NULL / not set - the default, which will mean that we haven't chosen a value yet.

**Comment by benbarden** [comment]
These options are now available when adding/editing games.

I'll keep this issue open as there is more to do - currently the fields don't do anything other than being stored.

No need to start filling them in yet - I'll see if these are available in the API first.

**Comment by benbarden** [comment]
Yes - there is some data on these:

- demo_availability (either true, or left out entirely)
- dlc_shown_b (either true, false, or missing)

**Comment by benbarden** [comment]
We probably don't need "Included in bundle" for digital. I'll take that out.

**Comment by benbarden** [comment]
I'm going to change "Discontinued" for digital games to "De-listed", and use this instead of what I suggested for #69 . The rest of that issue still stands - it will just use the format_digital field instead of needing another field for delisted.

**Comment by benbarden** [comment]
I've updated the new format fields from the API.

**Comment by benbarden** [comment]
Format option stats can be found here - https://www.switchscores.com/staff/games/dashboard

Amazon link page now includes physical titles only.

I'm going to call this done.

**Comment by cosmo0** [comment]
Awesome! I'll take a look later at all the "not set" games, and the limited editions.

**Comment by cosmo0** [comment]
@benbarden here are a few special cases:

- A few games have only been released in the US or Japan, like One Finger Death Punch 2, Puzzle & Dragons Gold, Dead or Alive XTreme 3 (and a lot of others). I mark them as "available" (even though it's a different store).
- 8-bit ADV Steins;Gate: digital only, available when purchasing Steins;Gate Elite in Japan. I marked it as available digitally (even though it's only in a bundle), and in a physical bundle (I assume it's available through the physical version of Steins;Gate, but I can't be sure)

**Comment by cosmo0** [comment]
@benbarden I'm putting Japan-only releases as "limited edition", the logic being that they're hard to find (you won't find them on Amazon or in brick-and-mortar store), and are actually often limited in print (they often become very hard to find after a few weeks/months). Maybe the entry should be "limited availability" ?

**Comment by cosmo0** [comment]
@benbarden I'm done updating the limited releases; I may have missed a few but I've done all the limited-run companies I know.

I haven't checked the "not set" yet.

There were quite a lot of "not available physically" errors... even for Nintendo-published games :/
