### ISSUE TITLE
New placeholder images

### ISSUE THREAD

**Issue by benbarden** [benbarden/switchscores#64]
Placeholder images still have the old site name. Any help creating new images would be good.

Logo grey (800x800) - https://www.switchscores.com/img/logo-grey.png

Logo grey wide (800x400) - https://www.switchscores.com/img/logo-grey-wide.png

Logo (800x800) - https://www.switchscores.com/img/logo.png - would be nice to have a new logo too.

**Comment by cosmo0** [comment]
Do you have the source for the logo in the favicon and background?

**Comment by benbarden** [comment]
Nope, you'll have to ask A.J. @videochums for those.

**Comment by cosmo0** [comment]
Ok, do they answer to Twitter DMs ? They don't follow anyone, and it often means that they don't really use that Twitter account except for publishing stuff.

**Comment by benbarden** [comment]
I can ask.

**Comment by cosmo0** [comment]
If you have the source I can edit it to create multiple sizes.

I'm bad at creating stuff (I'm not a designer) but I know Photoshop quite well to edit existing things.

**Comment by benbarden** [comment]
Looks like we don't have a source image to work from.

**Comment by benbarden** [comment]
Images are now available. I'll create a new task for replacing existing code.
