### ISSUE TITLE
Add a quick YouTube search link to Game Editor

### ISSUE THREAD

**Issue by cosmo0** [benbarden/switchscores#66]
I'm checking the "missing video" page, and there's one easy thing that would help a lot: adding a simple "search YT" link next to the "video url" field in the game edit page that points to a Youtube search like:

`https://www.youtube.com/results?search_query=trailer+$game_title`

That would save a lot of typing (so a lot of time)

**Comment by benbarden** [comment]
Updating the title to be more descriptive.

This is a great idea - although it probably needs #60 first!

**Comment by cosmo0** [comment]
Well, I can fill the Youtube trailers (I already started) even before you add the video to the game's page. It's much quicker to add a link :)

**Comment by cosmo0** [comment]
I thought you could just add a querystring parameter to an Amazon link to make it an affiliate? Anyway if you must have a special link I can't build them, I only have access to the "public" links.

**Comment by cosmo0** [comment]
> Have added the YouTube button

Thanks it's great! But could you add "switch" (as in "switch trailer")? Otherwise I get a lot of PS4/PC trailers at the top of the results.

**Comment by cosmo0** [comment]
Also, there's a bug when the game has a "&" in the title: https://www.switchscores.com/staff/games/edit/489

**Comment by benbarden** [comment]
Updated both of those. I'd say this is done now.
