### ISSUE TITLE
Duplicate companies

### ISSUE THREAD

**Issue by cosmo0** [benbarden/switchscores#67]
Here are a few companies that are duplicates, or close enough (subsidiaries...) and could be merged.

- [x] - 631 2K Games / 315 2K Sports
- [x] - 1237 Alawar Entertainment / 1549 Alawar Premium (public/corporate)
- [x] - 1552 Alliance / 558 Alliance Digital Media
- [x] - 701 Anuman / 1558 Anuman Interactive
- [x] - 1567 Atomicom / 1568 Atomicom Limited
- [x] - 108 Bandai Namco Entertainment / 189 Bandai Namco Studios
- [x] - 306 | Bethesda Game Studios / 307 | Bethesda Softworks
- [x] - 663 | Brain Seal Entertainment / 662 | Brain Seal Ltd
- [x] - 1598 | CD Projekt / 775 | CD Projekt Red
- [x] - 276 | Chorus Worldwide/ 1606 | Chorus Worldwide Games - **can't find the duplicate**
- [x] - 787 | Coatsink / 1607 | Coatsink Software - **can't find the duplicate**
- [x] - 1610 | Coffee Stain Publishing / 790 | Coffee Stain Studios
- [x] - 470 | Cooply / 471 | Cooply Solutions
- [x] - 1614 | Corecell / 646 | Corecell Technology
- [x] - 2047 | Corvostudio / 2019 | Corvostudio di Amadei Marco
- [x] - 1616 | Crazy Monkey / 564 | Crazy Monkey Studios
- [x] - 538 | Deep Silver / 674 | Deep Silver Fishlabs
- [x] - 823 | Devespresso Games / 230 | Devespresso Studios
- [x] - 52 | Digerati / 1629 | Digerati Distribution - **can't find the duplicate**
- [x] - 826 | Digital Melody / 259 | Digital Melody Games
- [x] - 838 | Double Fine / 839 | Double Fine Productions
- [x] - 848 | EA Canada / 590 | EA Originals / 1651 | EA Sports / 118 | Electronic Arts
- [x] - 1679 | Flying Tiger / 60 | Flying Tiger Entertainment
- [x] - 61 | Forever Entertainment / 1681 | Forever Entertainment S.A.
- [x] - 1700 | Ghostlight / 1701 | Ghostlight Limited
- [x] - 924 | Goblinz Studio / 1706 | GoblinzStudio
- [x] - 235 | Gust / 2021 | Gust Co. Ltd.
- [x] - 125 | Headup Games / 1722 | Headup GmbH
- [x] - 1724 | Herrero / 963 | Herrero Games
- [x] - 968 | High Horse Entertainment / 969 | High Horse Games
- [x] - 986 | illuCalab / 1015 | illuCallab
- [x] - 461 | Illumination Games / 987 | IlluminationGames
- [x] - 1233 | Intra Games / 1006 | Intragames
- [x] - 128 | Joindots / 1745 | Joindots GmbH
- [x] - 1034 | Kadokawa Games / 342 | Kadokawa Shoten
- [x] - 390 | King Art / 217 | King Art Games
- [x] - 524 | Klabater / 1759 | Klabater S.A.
- [x] - 539 | Koch Media / 1762 | Koch Media GmbH
- [x] - 73 | Koei Tecmo / 1763 | Koei Tecmo Europe
- [x] - 1052 | Kuju Entertainment / 1053 | Kuju Games
- [x] - 1055 | Kylotonn / 1056 | Kylotonn Games
- [x] - 1063 | Le Cartel / 1064 | Le Cartel Studio
- [x] - 1085 | Mad Mimic / 1086 | Mad Mimic Interactive
- [x] - 304 | Marvelous / 529 | Marvelous Europe / 1101 | Marvelous First Studio / 1188 | Marvelous USA
- [x] - 1806 | N-Fusion / 1137 | N-Fusion Interactive
- [x] - 1140 | Navila Software Japan / 1813 | Navila Software Japan G.K.
- [x] - 1820 | Night School / 574 | Night School Studio
- [x] - 80 | Nintendo / 198 | Nintendo EAD / 1162 | Nintendo EPD
- [ ] - 81 | Nippon Ichi Software / 239 | NIS America
- [x] - 1307 | Pocket Money Games / 1859 | Pocketmoneygames
- [x] - 1203 | QUByte Game Studio, LLC / 1322 | QUByte Interactive
- [x] - 1050 | Raw Fury / 178 | Raw Fury Games
- [x] - 339 | Ripstone / 1888 | Ripstone Games
- [x] - 1365 | Sand Sailor Studio / 1907 | SandSailorStudio
- [x] - 1913 | Sekai Games / 1914 | Sekai Project
- [x] - 1383 | Sims / 1183 | SIMS Co., Ltd.
- [x] - 277 | SMG Studio / 1391 | SMG Studios
- [x] - 95 | Square Enix / 1927 | Square Enix Europe
- [x] - 1204 | Storybird / 210 | Storybird Games
- [x] - 97 | System 3 / 1939 | System 3 Software
- [x] - 1443 | Tacs Games / 1941 | Tacs Games Limited
- [x] - 1449 | Technos / 325 | Technos Japan
- [x] - 180 | THQ Nordic / 1953 | THQ Nordic GmbH
- [x] - 1955 | Tiny Trinket Games / 1956 | Tiny Trinket Games SRL
- [x] - 152 | tinyBuild / 945 | tinyBuild Games
- [x] - 344 | Toybox / 158 | Toybox Games
- [x] - 221 | TT Fusion / 101 | TT Games
- [x] - 153 | Ubisoft / 438 | Ubisoft Milan / 494 | Ubisoft Montpellier / 1487 | Ubisoft Montreal / 434 | Ubisoft Paris / 1488 | Ubisoft San Francisco / 493 | Ubisoft Toronto
- [x] - 1979 | Unites / 346 | Unties
- [x] - 1981 | Uppercut Fames / 1500 | Uppercut Games
- [x] - 1995 | Wastelands / 1513 | Wastelands Interactive
- [x] - 1514 | WayForward / 324 | WayForward Technologies
- [x] - 519 | Wired Productions / 2006 | Wired Productions Limited
- [x] - 1522 | Young Fun Games / 1523 | Young Fun Studio

**Comment by benbarden** [comment]
I've started on these. So far we've got:

- 2K
- Alawar
- Alliance
- Anuman Interactive
- Atomicom

**Comment by cosmo0** [comment]
I stopped at Gust, I'll check the rest tomorrow.

**Comment by cosmo0** [comment]
- 125 | Headup Games / 1722 | Headup GmbH
- 1724 | Herrero / 963 | Herrero Games
- 968 | High Horse Entertainment / 969 | High Horse Games
- 986 | illuCalab / 1015 | illuCallab
- 461 | Illumination Games / 987 | IlluminationGames
- 1233 | Intra Games / 1006 | Intragames
- 128 | Joindots / 1745 | Joindots GmbH
- 1034 | Kadokawa Games / 342 | Kadokawa Shoten
- 390 | King Art / 217 | King Art Games
- 524 | Klabater / 1759 | Klabater S.A.
- 539 | Koch Media / 1762 | Koch Media GmbH
- 73 | Koei Tecmo / 1763 | Koei Tecmo Europe
- 1052 | Kuju Entertainment / 1053 | Kuju Games
- 1055 | Kylotonn / 1056 | Kylotonn Games
- 1063 | Le Cartel / 1064 | Le Cartel Studio
- 1085 | Mad Mimic / 1086 | Mad Mimic Interactive
- 304 | Marvelous / 529 | Marvelous Europe / 1101 | Marvelous First Studio / 1188 | Marvelous USA
- 1806 | N-Fusion / 1137 | N-Fusion Interactive
- 1140 | Navila Software Japan / 1813 | Navila Software Japan G.K.
- 1820 | Night School / 574 | Night School Studio
- 80 | Nintendo / 198 | Nintendo EAD / 1162 | Nintendo EPD
- 81 | Nippon Ichi Software / 239 | NIS America
- 1307 | Pocket Money Games / 1859 | Pocketmoneygames
- 1203 | QUByte Game Studio, LLC / 1322 | QUByte Interactive
- 1050 | Raw Fury / 178 | Raw Fury Games
- 339 | Ripstone / 1888 | Ripstone Games
- 1365 | Sand Sailor Studio / 1907 | SandSailorStudio
- 1913 | Sekai Games / 1914 | Sekai Project
- 1383 | Sims / 1183 | SIMS Co., Ltd.
- 277 | SMG Studio / 1391 | SMG Studios
- 95 | Square Enix / 1927 | Square Enix Europe
- 1204 | Storybird / 210 | Storybird Games
- 97 | System 3 / 1939 | System 3 Software
- 1443 | Tacs Games / 1941 | Tacs Games Limited
- 1449 | Technos / 325 | Technos Japan
- 180 | THQ Nordic / 1953 | THQ Nordic GmbH
- 1955 | Tiny Trinket Games / 1956 | Tiny Trinket Games SRL
- 152 | tinyBuild / 945 | tinyBuild Games
- 344 | Toybox / 158 | Toybox Games
- 221 | TT Fusion / 101 | TT Games
- 153 | Ubisoft / 438 | Ubisoft Milan / 494 | Ubisoft Montpellier / 1487 | Ubisoft Montreal / 434 | Ubisoft Paris / 1488 | Ubisoft San Francisco / 493 | Ubisoft Toronto
- 1979 | Unites / 346 | Unties
- 1981 | Uppercut Fames / 1500 | Uppercut Games
- 1995 | Wastelands / 1513 | Wastelands Interactive
- 1514 | WayForward / 324 | WayForward Technologies
- 519 | Wired Productions / 2006 | Wired Productions Limited
- 1522 | Young Fun Games / 1523 | Young Fun Studio

OK now I know why you'd prefer to add the companies manually... 😓 they can't even spell their name right twice 😂

There are probably others, I didn't check extensively.

**Comment by benbarden** [comment]
I've merged your list into the first post and changed it to a checklist.

**Comment by benbarden** [comment]
A few of these only have one record in the list. I guess you did these already? If so could you tick them off?

So far we have:
- 276 | Chorus Worldwide/ 1606 | Chorus Worldwide Games - can't find the duplicate
- 787 | Coatsink / 1607 | Coatsink Software - can't find the duplicate
- 52 | Digerati / 1629 | Digerati Distribution - can't find the duplicate

**Comment by cosmo0** [comment]
Yeah I've already manually merged like 10 companies or so, when one of the two had less than 5 games. I don't remember the ones so if you can't find one of the duplicates, I've already done it.

**Comment by cosmo0** [comment]
Manually cleaned:

- THQ Nordic / THQ Nordic GmgH
- GoblinzStudio / Goblinz Studio
