### ISSUE TITLE
Generate images on category homepage

### ISSUE THREAD

**Issue by cosmo0** [benbarden/switchscores#68]
I think the categories list is a bit difficult to "parse", especially for people who don't know what the categories have inside (what's the difference between adventure and puzzle/adventure?)

Displaying sample games might help people better understand and find what they're looking for.

What do you think of something like that? https://codepen.io/cosmo0/pen/abBvNoB

There's the problem of categories with zero game (fighting and platformer), but it can be easily solved by using a mix of games in sub-categories.

**Comment by benbarden** [comment]
This is similar to #57 .

I think this page is ok though, at least for now. The pages I'd like to improve are the pages that list the games in each category. I'm sure those can be better.

**Comment by cosmo0** [comment]
Honestly I still think it would be better with images, but I don't have strong feelings about it.

**Comment by benbarden** [comment]
I've got this working in #57 , but I think categories and tags work better as lists of text - because there are a lot.

Series and probably collections work ok with images.

I think we shouldn't do this for categories.

**Comment by cosmo0** [comment]
I still think it would help users with the categories. Because they might not be knowledgeable in what a genre entails: what is a metroidvania? Or a dungeon crawler? But maybe seeing a few names they recognize would help.

Seeing my proposal again, it's obvious it doesn't work. I'll try to think of something else.

**Comment by benbarden** [comment]
How about if the category homepage didn't show subcategories? A similar layout to the series landing page would work if it didn't need to display any kind of hierarchy. Then when you go into a category, the subcategories could show at the top, with images - which would solve the issue you mentioned where they don't stand out enough.

**Comment by cosmo0** [comment]
I'm not sure. Some categories, like fighting games, have zero games inside, so it'd be weird to click in a category and have nothing inside. And some sub-categories could be in multiple categories, like Tactical RPG could be under RPG or Strategy, and unless you already know where to look, it'd be annoying to browse.

**Comment by benbarden** [comment]
The first part wouldn't happen though - when clicking into a category, you'd still see the games. This was just to say that subcategories would also show when you click through to a category - as they do now, but more prominent.

As for not being able to find a category, we could still have the list view. So by default, you'd see just the top categories with images. But you could have a link "show all as list" and that would show the current view.

**Comment by cosmo0** [comment]
Hm, I think between this solution and the current state, I prefer the current state.

Do you have a public API that I could use to make mockups of the categories list?

**Comment by benbarden** [comment]
Not an API of the categories. I thought you'd already done a mockup? (see first post)

**Comment by cosmo0** [comment]
Yeah but I had to copy/paste manually the image URLs. Nevermind, I'm not sure I'll have the time to do it anyway.
