### ISSUE TITLE
De-listed games

### ISSUE THREAD

**Issue by benbarden** [benbarden/switchscores#69]
Some games have an fs_id that was originally linked to the API, but later the link is broken. This could be recorded in a field `is_delisted`.

Approach/uses:

- [x] write a new command to set/unset this field. This would need to run after the eShop update scripts, but before `UpdateGameRanks`
- [x] show a label somewhere on the game page saying "De-listed"
- [x] change the blurb to say "De-listed" rather than upcoming
- [x] do not give de-listed games a rank, although they can keep their average rating
- [x] do not include de-listed games in the stats for released games, ranked, or unranked
- [x] do not show de-listed games on any of the browse games pages - i.e. browse by title, date, category, tag, series
- [x] do not show de-listed games on any pages listing unranked games
- [x] do not show de-listed games in sitemaps
- [x] update the current broken link icon in Staff to use this new field (it's a bit more reliable)
- [x] set `is_delisted` to 0 if updating the link for a game

Not changed:
- _update the broken Nintendo link list to use this new field_ - Won't do, this is a different query
- _create a new page under /games with a list of the de-listed games. Not super useful but at least they would then be linked from somewhere_ - Won't do, not essential

I'd like to get the main areas updated first - others can be done later. Are there any major things I've missed?

**Comment by cosmo0** [comment]
I think it's all good

**Comment by cosmo0** [comment]
I was thinking: what about keeping the games in the lists, but graying them out, and/or displaying a "delisted" banner?

Something like that: https://codepen.io/cosmo0/pen/XWNXEBq

![image](https://user-images.githubusercontent.com/3973850/107022529-d1ad6a80-67a5-11eb-801e-13e5d848fd31.png)

That way someone who heard of a game can still find it easily (and see that it's not available anymore), but it's clear that it's been removed.

Or in a special "delisted" list under ranked/unranked?

**Comment by benbarden** [comment]
The de-listed field is now set as part of #61 , i.e. the format_digital dropdown. I'll get to some of the other changes soon.

**Comment by benbarden** [comment]
This is all done. Quite a few changes and I might have missed some things. If you find any problems please file a new issue.
