### ISSUE TITLE
Suggestion: add price info in games lists

### ISSUE THREAD

**Issue by cosmo0** [benbarden/switchscores#7]
Many people have a max budget when looking for a game. Here are a few idea to help them:

- Display the price of the game in the games lists (like https://www.switchscores.com/games/by-category/adventure )
- Highlight the price if the game is on sale
- Add a "max price" filter in the games lists (but I have no idea how to display it)

**Comment by benbarden** [comment]
This is a good idea, but potentially quite a big job as it affects lots of pages. I don't think the current layout really works for big categories at the moment. I'd prefer to work on the layout in general and include the price as part of that.

**Comment by benbarden** [comment]
The price and on sale info are now on the Snapshot tab of the category pages:
https://www.switchscores.com/games/by-category/metroidvania

**Comment by benbarden** [comment]
Prices and on sale info are now in the tables on category pages.
