### ISSUE TITLE
Video types

### ISSUE THREAD

**Issue by cosmo0** [benbarden/switchscores#70]
As discussed on Twitter, some games don't have trailers (mostly smaller indie games and retro re-releases like Arcade Archives), but all of them have at least one "let's play" available.

There seem to be more of them than I thought, so as you suggested, it could be good to either have a field to specify the kind of video (trailer/gameplay) or a second "video" field.

Could you make a SQL query to get the games (and their video URL), using the Audit table, to get the games that had the `video_url` field modified between february 1st (morning) and february 3rd (evening)? I'll check to remove the non-trailers videos.

**Comment by benbarden** [comment]
What types of video are there? What would the text on the button be for each type?

**Comment by cosmo0** [comment]
I think just "trailer" and "gameplay" videos.

**Comment by benbarden** [comment]
This is live. All games with existing video links have had their video type updated to "Trailer". The button text on the game page will change depending which video type you choose.

**Comment by benbarden** [comment]
The "no video URL" filter is now a "no video type" filter. If there's no video available, choose "No video" in the video type dropdown and the game will drop off the filter.
