### ISSUE TITLE
Games marked as de-listed in the API but can be found and bought on the site

### ISSUE THREAD

**Issue by cosmo0** [benbarden/switchscores#72]
A few games are marked as "not available" in the API, but they are present on the website.

- Doom Eternal https://www.nintendo.co.uk/Games/Nintendo-Switch/DOOM-Eternal-1886089.html
- Starlink Battle for Atlas https://www.nintendo.co.uk/Games/Nintendo-Switch/Starlink-Battle-for-Atlas-1388917.html
- Super Meat Boy Forever https://www.nintendo.co.uk/Games/Nintendo-Switch-download-software/Super-Meat-Boy-Forever-1883676.html
- The Drama Queen Murder https://www.nintendo.co.uk/Games/Nintendo-Switch-download-software/The-Drama-Queen-Murder-1608907.html
- Warriors Orochi 4 https://www.nintendo.co.uk/Games/Nintendo-Switch/WARRIORS-OROCHI-4-1452514.html
- Wolfenstein Youngblood https://www.nintendo.co.uk/Games/Nintendo-Switch/Wolfenstein-Youngblood-Standard-Edition-1575858.html

Maybe add a field "broken API entry, here's the nintendo.co.uk URL to override it"?

There are also two games that are available on the FR site but not the UK (???). Not sure what to do with them, or if we even ought to care (they're not good games anyway).

- Super Destronaut DX https://www.nintendo.fr/Jeux/Jeux-a-telecharger-sur-Nintendo-Switch/Super-Destronaut-DX-1402533.html
- Sword of the Guardian https://www.nintendo.fr/Jeux/Jeux-a-telecharger-sur-Nintendo-Switch/Sword-of-the-Guardian-1473844.html

**Comment by benbarden** [comment]
Yeah, I think something's gone wrong here with the data - I checked a few and they're not in the API. I agree with your idea to have a manual link if these are broken. I can then update the de-listed checker so it ignores anything where there's a manual link set.

**Comment by cosmo0** [comment]
Maybe there are others wrongly de-listed, but these ones are pretty "big names" and stand out (except Drama Queen Murder and the two others that are in the FR store but not the UK).

I've checked the rest of the list, and they all seem to be correctly de-listed, only these ones are wrong.

**Comment by benbarden** [comment]
Ok, I've added a new field - Nintendo store URL override - which you can find when editing games. If you fill in that field, the Digital availability will not be set to De-listed.

The override URL isn't displayed anywhere yet, but it can be - I'd guess that's useful? For now though, this at least solves the original issue you raised.

**Comment by cosmo0** [comment]
I've updated the games to add the URL.

I think it should be displayed in the same place as the API URL ?

**Comment by benbarden** [comment]
Done - it'll now appear on the public game page, and on the game detail page in Staff. I don't think there are any others.

**Comment by cosmo0** [comment]
Nice !
