### ISSUE TITLE
Data fill campaigns

### ISSUE THREAD

**Issue by cosmo0** [benbarden/switchscores#73]
Just a list of all the things there are 

- [ ] Video trailers (or gameplay when #70 is done)
- [x] Amazon links
- [x] Create and fill tags
- [x] Games without publishers
- [ ] Companies URL/Twitter

**Comment by benbarden** [comment]
#70 is done :)

**Comment by cosmo0** [comment]
@benbarden games without publishers: done! The only ones remaining are the de-listed games. Could you remove them from the list please? https://www.switchscores.com/staff/partners/data-cleanup/games-with-missing-publisher

I don't think I'll do "games without developer": there are a LOT missing, and I don't think it's a very interesting info.

I manually de-duplicated companies but there are still a lot of duplicates - see #67

**Comment by benbarden** [comment]
Excellent - thanks so much! 🙌 

I've removed de-listed games. To make it work I had to do:

`WHERE format_digital <> 'De-listed' OR format_digital IS NULL`

That will catch blanks as well. So if the Digital format option is blank, it will show in the list.

**Comment by benbarden** [comment]
I've ticked off Amazon links as a lot of games don't have them, and also tags, as the list is far too long to be manageable.

Videos (and most of these) are on the Games dashboard so they can be easily tracked.

Company URLs / Twitter IDs, I'll add a task to create a Games company dashboard instead. The list page is too slow to load and some stats / filters would be better.
