### ISSUE TITLE
Staff - Partners: quick add partners to game

### ISSUE THREAD

**Issue by benbarden** [benbarden/switchscores#74]
Split from #65 

Add some buttons to this page:
https://www.switchscores.com/staff/games/partner/5312/list

The buttons would allow you to click and have the developer or publisher added to the game.

**Comment by cosmo0** [comment]
Maybe you could add buttons next to the data sources if a partner name matches?

Like in this example, "Ant Workshop" would have been found but not "Mike Bithell Games":

<img width="1192" alt="Capture d’écran 2021-02-10 à 23" src="https://user-images.githubusercontent.com/3973850/107579391-590b3b80-6bf5-11eb-8d35-ac058375f98c.png">

**Comment by benbarden** [comment]
Yes, that's basically what I was thinking, although I will change the layout a bit as there isn't much space.

Anything that isn't in the database could still have a button to create it and apply it.

**Comment by benbarden** [comment]
I made a change so that when a game is added to the site from the Nintendo API data, the publisher is auto-linked if the name matches a games company. If it doesn't match, we'd need to manually assign it anyway. So this isn't needed anymore.
