### ISSUE TITLE
Feature request: add a link to the admin from the front

### ISSUE THREAD

**Issue by cosmo0** [benbarden/switchscores#78]
Sometimes it's easier to browse games from the front-office.

For instance, to fill the tags, I'd like to fill the "best games" first, so I'll check the "top rated" and best games by category.

Could you add a link to the admin page ( https://www.switchscores.com/staff/games/detail/4610 ) from the user page ( https://www.switchscores.com/games/4610/monster-hunter-rise ) ?

Thanks !

**Comment by benbarden** [comment]
Done!

**Comment by cosmo0** [comment]
Thanks!
