### ISSUE TITLE
Suggestion: allow user to set their store country

### ISSUE THREAD

**Issue by cosmo0** [benbarden/switchscores#8]
Nintendo Europe stores are backed by the same DB, and so have basically the same URL:

- UK: https://www.nintendo.co.uk/Games/Nintendo-Switch/The-Legend-of-Zelda-Link-s-Awakening-1514327.html
- FR: https://www.nintendo.fr/Jeux/Nintendo-Switch/The-Legend-of-Zelda-Link-s-Awakening-1514327.html
- IT: https://www.nintendo.it/Giochi/Nintendo-Switch/The-Legend-of-Zelda-Link-s-Awakening-1514327.html
- PT: https://www.nintendo.pt/Jogos/Nintendo-Switch/The-Legend-of-Zelda-Link-s-Awakening-1514327.html

Feature idea: allow users to set their country in their preferences (in the dashboard), and change the eShop link accordingly in the game's page.

The Nintendo EU countries are listed here: http://www.nintendo-europe.com/

**Comment by benbarden** [comment]
While useful, this is one of those ideas that would be more beneficial when we have more members. So few people sign up that most people won't see it. Also, I think it inevitably leads to requests to do other countries too, which is a much more difficult task.

**Comment by cosmo0** [comment]
How many users are there currently?

**Comment by benbarden** [comment]
Difficult to give an exact number, because some are reviewers or games companies. Regular members is below 100. Active members is quite low. I think it would be worth looking at some ways to bring in members - which can include adding features, but perhaps making better use of the popular pages on the site could help.

**Comment by cosmo0** [comment]
I think there are a few ways to get more people.

- make the site more useable for international users: for instance, currently, the prices are displayed only in £, which is only useful for UK users. I think displaying the price in € and $ (and US sales) would help a bit, although not a lot.
- create unique features ; I really think my idea of a browser extension that inserts infos directly in the page (see #19) would be a game-changer for many people: a simple way to see if this "-90% game" is worth it. Although it's probably not easy, especially since ideally it would require to match the games to all EU stores and the US one.
- just talk more about the site. Get people to talk about it on Twitter, Facebook, Reddit, Resetera, whatever. It's also one of the more time consuming and less rewarding ways, especially since you don't gain money from visitors.

**Comment by benbarden** [comment]
Moving to separate backlog
