### ISSUE TITLE
Use Youtube API to search for videos

### ISSUE THREAD

**Issue by cosmo0** [benbarden/switchscores#81]
There are still 2700 videos to fill, and it takes a LOT of time.

One thing would help me a lot: to be able to fill the video field in a small number of clicks:

- The "search Youtube" button would open a Bootstrap Modal listing the top 10 videos with the search query (see https://developers.google.com/youtube/v3/docs/search/list ) with their title, description and thumbnail.
- Clicking on a search result would fill the Video URL field and set the "video type" to trailer.
- A "manual search" button would open Youtube with the pre-filled search query (like it does today)

**Comment by benbarden** [comment]
Moving to separate backlog
