### ISSUE TITLE
De-listed games on landing pages

### ISSUE THREAD

**Issue by benbarden** [benbarden/switchscores#82]
With this de-listed game - https://www.switchscores.com/games/5537/future-aero-racing-s-ultra-far-s-ultra

we've ended up with 3/3 reviews, because de-listed games aren't given a rank.

![Screenshot 2021-04-22 at 08 37 26](https://user-images.githubusercontent.com/628824/115674913-0ad98d80-a346-11eb-8b05-d14fd4443afb.png)

Some options that might be better:

- remove the release date and put "De-listed"
- remove "3/3 reviews" altogether

**Comment by cosmo0** [comment]
- remove de-listed games from the landing pages :P

**Comment by benbarden** [comment]
I mean yeah, I could do that :) but may not be a bad thing to add some checks to the template too.

**Comment by benbarden** [comment]
I spotted that Skate City was de-listed overnight, and was showing 4/3 reviews.

So, I've made two changes.

I've removed de-listed games from the Recently ranked section on the homepage.

And in case any games show up, the reviews will now say "De-listed".
