### ISSUE TITLE
Tag pages are not sorted

### ISSUE THREAD

**Issue by cosmo0** [benbarden/switchscores#86]
https://www.switchscores.com/games/by-tag/escape-room

It doesn't seem to be sorted by release date, or by score, or by title.

**Comment by benbarden** [comment]
The sort I'm using for those pages is:

```            ->orderBy('games.rating_avg', 'desc')
            ->orderBy('games.eu_release_date', 'desc');```

i.e. Show highest rated games first (for those that are ranked), then show the newest releases next.

How about if the layout was the same as the new category pages?

**Comment by cosmo0** [comment]
> How about if the layout was the same as the new category pages?

Yeah maybe? As it stands it's pretty weird, I didn't understand the order at all.

**Comment by benbarden** [comment]
I've sorted tag pages by title for now.
