### ISSUE TITLE
Don't display "ranked" list when there are no ranked games

### ISSUE THREAD

**Issue by cosmo0** [benbarden/switchscores#9]
Some categories don't have ranked games and probably never will: educational, mahjong, casino, game show, bowling.

In this case, don't display the "ranked" list because it takes a lot of space for nothing.

**Comment by benbarden** [comment]
I guess you mean pages like this?
https://www.switchscores.com/games/by-category/adventure

I'm thinking of doing a bigger redesign for those pages, which might be similar to the Games homepage:
https://www.switchscores.com/games

Still thinking about how best to do that though.

**Comment by cosmo0** [comment]
Yes the "by-category" pages.

I'm not a fan of horizontal scrolling, you can't use your mouse wheel.

I think the "by-category" page could use an improvement but I'm not sure how. At least they're very useable right now.

**Comment by benbarden** [comment]
One more that relates to the category page designs.

I agree about the horizontal scrolling, although maybe worth saying that most visitors are on mobile. I have been experimenting with putting arrows on the page so you can scroll with the mouse.

**Comment by benbarden** [comment]
This is done. Example page - https://www.switchscores.com/games/by-category/bowling

I've also changed the Ranked/Unranked headings a bit - https://www.switchscores.com/games/by-category/visual-novel

**Comment by cosmo0** [comment]
Nice!

The labels are a nice touch. What about "3 reviews or more" / "2 reviews or less" ?
