### ISSUE TITLE
New games do not have format options set

### ISSUE THREAD

**Issue by cosmo0** [benbarden/switchscores#91]
https://www.switchscores.com/staff/partners/data-cleanup/games-with-missing-publisher

Some games stay in the list despite having a publisher set.

**Comment by benbarden** [comment]
Which ones shouldn't be there? I'm not seeing any issues...

**Comment by cosmo0** [comment]
All of them. I've set the publishers for all of them.

**Comment by benbarden** [comment]
OK - this is actually a data issue.

This week, I updated the games on the site a day later than usual. Normally I do the updates on a Saturday. Every night, there is a cron that imports the latest data from the Nintendo API. At the end of the import, it marks all games as "Available" where they have an API link, and "De-listed" where they don't - unless there's a store URL override. I re-ran that process and the list should now be ok.

**Comment by cosmo0** [comment]
So the list is not updated in real-time? Sometimes they disappear from the list when I set a publisher, sometimes not. What's the rule?

**Comment by cosmo0** [comment]
OK thanks :)

**Comment by benbarden** [comment]
Fixed.
