### ISSUE TITLE
Categorisation dashboard: useless "category/tag matches"

### ISSUE THREAD

**Issue by cosmo0** [benbarden/switchscores#92]
https://www.switchscores.com/staff/categorisation/dashboard

The two blocks "category match" and "tag match" are pretty useless, as most games don't put relevant information in their title.

**Comment by benbarden** [comment]
Done - I've kept series matches in case those are still useful?

**Comment by cosmo0** [comment]
Yes series match is useful. There are a few "false positives" but I don't mind much.
