### ISSUE TITLE
Tags in public pages

### ISSUE THREAD

**Issue by cosmo0** [benbarden/switchscores#94]
I've been adding tags to a lot of games lately, but I think there could be improvements in how they're used.

- [Game page](https://www.switchscores.com/games/2850/wilmots-warehouse): by default, the tags are hidden out of view. Maybe put them under the header image?
- [List of games](https://www.switchscores.com/games/by-category/adventure): display the tags... somewhere ^^
- [Browse by tag](https://www.switchscores.com/games/by-tag): improve layout?

**Comment by benbarden** [comment]
I've updated the game page, and the browse by tag page:
https://www.switchscores.com/games/by-tag

Does your issue #99 remove the need for changing the lists? As you've suggested having a search page with multiple criteria, instead of adding info such as this to list pages?

**Comment by cosmo0** [comment]
Honestly I'm not a fan of having to open the tag categories to see the tags. Maybe just have the tags not in a vertical list, if you think there are too many?

I agree it'll be difficult to add the tags to the list as they are now.

**Comment by benbarden** [comment]
Ok, how's this?
https://www.switchscores.com/games/by-tag

**Comment by cosmo0** [comment]
Nice! Not sure about the "tag" icon but it's much better.

**Comment by benbarden** [comment]
Great, thanks - I'll close this :)
