### ISSUE TITLE
Add entries in "staff home" page

### ISSUE THREAD

**Issue by cosmo0** [benbarden/switchscores#97]
In https://www.switchscores.com/staff

Please add shortcuts to:

- games with no category: https://www.switchscores.com/staff/categorisation/migrations/category/all-games-with-no-category
- games with missing publishers: https://www.switchscores.com/staff/partners/data-cleanup/games-with-missing-publisher
- games without tags (see #93)

**Comment by benbarden** [comment]
Games without tags is now on the Staff index.
