### ISSUE TITLE
Tags are not displayed in "upcoming" games

### ISSUE THREAD

**Issue by cosmo0** [benbarden/switchscores#98]
https://www.switchscores.com/games/5844/port-royale-4

The game has tags but they don't appear in the "public" page.

**Comment by benbarden** [comment]
This is because if you go to the tag pages, upcoming games won't show there either. It would be odd if the tags showed on the game page but clicking through to the tag page didn't show the game.

Is it useful to show upcoming / not yet released games on tag pages?

**Comment by cosmo0** [comment]
I don't know. It sure would be weird if clicking on a tag from the game's page didn't show the game in the list. But maybe people could be interested in seeing upcoming games in tags? Now that I think about it, maybe even games by categories should have a tab "upcoming" ?

**Comment by benbarden** [comment]
We could, but it will be a short list - normally there are < 100 upcoming games at any one time, so upcoming by category would be very low numbers.

Perhaps I could change the layout of this page a bit - https://www.switchscores.com/games/upcoming

**Comment by benbarden** [comment]
As a start, maybe worth adding the category to the upcoming page, as I do here - https://www.switchscores.com/games/on-sale

**Comment by cosmo0** [comment]
Maybe more than adding additional stuff on existing pages, create a full-fledge search page? I'll create an issue.

**Comment by benbarden** [comment]
In that case, do we still need this issue or can it be closed?

**Comment by cosmo0** [comment]
ok
