### ISSUE TITLE
Full "search" page

### ISSUE THREAD

**Issue by cosmo0** [benbarden/switchscores#99]
Currently there are multiple "list" pages, and the only way to search is by simple title.

Rather than adding stuff on existing lists, I suggest creating a full-fledged search page with multiple criterias:

- title
- score (min/max)
- category
- series
- tag(s)
- price (min/max)
- release date (min/max)
- physical release available
- demo available
- number of players

**Comment by benbarden** [comment]
I've got a version of this working - https://www.switchscores.com/games/search

Done so far:

- Title
- Minimum score
- Category
- Series
- Collection - (not on your list)
- Maximum price

Not yet done:

- Release date
- Physical release
- Demo
- Number of players

Difficult to do or not useful:

- Tag - will be difficult to do. Either choose one tag from a very long dropdown (may slow things down), or multi-select (much more difficult)
- Maximum score - doesn't seem useful
- Minimum price - doesn't seem useful

**Comment by benbarden** [comment]
Bonus feature: if you choose a top-level category, any subcategories will be included in the results.

**Comment by benbarden** [comment]
Release year dropdown is down.

One issue is that the minimum price option ignores sale prices. So if you search with a minimum price of 20, the game has a standard price of 25 but is currently reduced to 15, it won't show in the results. Best way to fix this would be to copy the sale price to a field that I can search by more easily. That's not a huge change, but it affects a few parts of the site.

**Comment by benbarden** [comment]
I'm going to close this as the bulk of the work is done. Anything else can be added as new issues.
